import{REGLAS,VERSION}from'./config.js';import{init as initStorage}from'./storage.js';import{initOfflineStorage}from'./offline-storage.js';import{initUserRoles,getUserRole}from'./user-roles.js';import{buildNav,setupEvents,destroyCharts}from'./ui.js';import{initAuth}from'./mod-auth.js';import{initSync}from'./sync-engine.js';
import{render as renderDashboard,init as initDashboard}from'./dashboard.js';
import{render as renderEmpleados,init as initEmpleados}from'./empleados.js';
import{render as renderEntregas,init as initEntregas}from'./entregas.js';
import{render as renderProveedores,init as initProveedores}from'./proveedores.js';
import{render as renderInventario,init as initInventario}from'./inventario.js';
import{render as renderCategorias,init as initCategorias}from'./categorias.js';
import{render as renderImportar,init as initImportar}from'./importar.js';
import{render as renderConfig,init as initConfig}from'./config-view.js';
import{render as renderAdminDash,init as initAdminDash}from'./admin-dashboard.js';
import{render as renderAdvancedReports,init as initAdvancedReports}from'./advanced-reports.js';import{render as renderExportAuditoria,init as initExportAuditoria}from'./export-auditoria.js';import{render as renderUsuarios,init as initUsuarios}from'./users.js';import{render as renderAreas,init as initAreas}from'./areas-config.js';import{render as renderCentroCostos,init as initCentroCostos}from'./centro-costos.js';import{render as renderStockUniformes,init as initStockUniformes}from'./stock-uniformes.js';import{render as renderBitacora,init as initBitacora}from'./bitacora.js';import{render as renderInventarioSKU,init as initInventarioSKU}from'./inventario-sku.js';import{render as renderEntregaSKU,init as initEntregaSKU}from'./entrega-sku.js';import{render as renderDevolucionSKU,init as initDevolucionSKU}from'./devolucion-sku.js';import{render as renderRecepcion,init as initRecepcion}from'./recepcion.js';import{render as renderEntregasPersonal,init as initEntregasPersonal}from'./entregas.js';import{render as renderSalidasAlmacen,init as initSalidasAlmacen}from'./salidas-almacen.js';import{render as renderDevoluciones,init as initDevoluciones}from'./devoluciones.js';import{render as renderReportesHub,init as initReportesHub}from'./reportes-hub.js';import{render as renderDotacion,init as initDotacion}from'./dotacion.js';
const views={dashboard:{render:renderDashboard,init:initDashboard},empleados:{render:renderEmpleados,init:initEmpleados},entregas:{render:renderEntregas,init:initEntregas},proveedores:{render:renderProveedores,init:initProveedores},inventario:{render:renderInventario,init:initInventario},categorias:{render:renderCategorias,init:initCategorias},importar:{render:renderImportar,init:initImportar},config:{render:renderConfig,init:initConfig},admin:{render:renderAdminDash,init:initAdminDash},'admin-dashboard':{render:renderAdminDash,init:initAdminDash},usuarios:{render:renderUsuarios,init:initUsuarios},areas:{render:renderAreas,init:initAreas},'centro-costos':{render:renderCentroCostos,init:initCentroCostos},'stock-uniformes':{render:renderStockUniformes,init:initStockUniformes},bitacora:{render:renderBitacora,init:initBitacora},'advanced-reports':{render:renderAdvancedReports,init:initAdvancedReports},'export-auditoria':{render:renderExportAuditoria,init:initExportAuditoria},'inventario-sku':{render:renderInventarioSKU,init:initInventarioSKU},'entrega-sku':{render:renderEntregaSKU,init:initEntregaSKU},'devolucion-sku':{render:renderDevolucionSKU,init:initDevolucionSKU},recepcion:{render:renderRecepcion,init:initRecepcion},'entregas-personal':{render:renderEntregasPersonal,init:initEntregasPersonal},'salidas-almacen':{render:renderSalidasAlmacen,init:initSalidasAlmacen},devoluciones:{render:renderDevoluciones,init:initDevoluciones},reportes:{render:renderReportesHub,init:initReportesHub},dotacion:{render:renderDotacion,init:initDotacion}};window.views=views;
let currentView='dashboard';
function viewFromHash(){return(location.hash.slice(1)||'').split('?')[0]||'';}
function normalizeView(v){return((v||'').split('?')[0]||'dashboard');}
function navigate(v){currentView=views[normalizeView(v)]?normalizeView(v):'dashboard';history.pushState({v:currentView},'','#'+currentView);buildNav(currentView);render();}
function render(){destroyCharts();const m=document.getElementById('mainContent');const view=views[currentView]||views.dashboard;m.innerHTML=view.render();if(view.init)view.init();}
window.addEventListener('popstate',e=>{const v=normalizeView((e.state&&e.state.v)||viewFromHash()||'dashboard');currentView=views[v]?v:'dashboard';buildNav(currentView);// No hay detach/cleanup global; render() limpia charts antes de pintar.
render();});
(async function(){initStorage(REGLAS);initUserRoles();if(!initAuth()){return;}await initOfflineStorage().catch(e=>console.warn('[OFFLINE]',e));const role=getUserRole();const isOp=role==='operador';const defView=isOp?'empleados':'dashboard';const _v=normalizeView(viewFromHash()||defView);currentView=(views[_v]&&!(isOp&&_v==='dashboard')&&!(role==='consulta'&&(_v==='admin'||_v==='admin-dashboard')))?_v:defView;buildNav(currentView);setupEvents(navigate);render();console.log('[ASSA ABLOY] Sistema de Uniformes v'+VERSION+' — Listo.');// Iniciar sync con Supabase en segundo plano (no bloquea UI)
initSync().catch(e=>console.warn('[SYNC] Error al iniciar:',e));})();
