import{VERSION}from'./config.js';import{getStore}from'./storage.js';import{calcStats,calcStatsArea}from'./rules.js';import{buildAreaBadge,createChart}from'./ui.js';import{getAreaNames}from'./areas-config.js';import{fmt,fmtMoney}from'./utils.js';
function areaIcon(name){const n=(name||'').toUpperCase();if(n.includes('PLANT'))return{icon:'fa-industry',color:'#2563eb'};if(n.includes('MANTEN')||n.includes('MECANIC')||n.includes('TALLER'))return{icon:'fa-tools',color:'#d97706'};if(n.includes('SUPERV'))return{icon:'fa-user-tie',color:'#7c3aed'};if(n.includes('PUERTA'))return{icon:'fa-door-open',color:'#059669'};if(n.includes('MATERIA'))return{icon:'fa-boxes',color:'#0891b2'};if(n.includes('TULT'))return{icon:'fa-building',color:'#dc2626'};if(n.includes('BRUK'))return{icon:'fa-hard-hat',color:'#ea580c'};if(n.includes('ADMIN')||n.includes('OFIC'))return{icon:'fa-briefcase',color:'#475569'};if(n.includes('ALMAC'))return{icon:'fa-warehouse',color:'#854d0e'};if(n.includes('SEGUR'))return{icon:'fa-shield-alt',color:'#1d4ed8'};return{icon:'fa-layer-group',color:'#64748b'};}
export function render(){
const s=calcStats();const st=getStore();const areas=getAreaNames();
const now=new Date();const mes=now.toLocaleDateString('es-MX',{month:'long',year:'numeric'});
const totalEnt=st.entregas.length;const entConFirma=st.entregas.filter(e=>e.firma).length;
const gastoUnif=st.proveedores.reduce((t,p)=>t+p.cantidad*p.precioUnitario,0);
const gastoAlm=(st.comprasAlmacen||[]).reduce((t,c)=>t+c.cantidad*c.precioUnitario,0);
const gastoTotal=gastoUnif+gastoAlm;
const alertasStock=(st.inventario||[]).filter(i=>i.minStock>0&&i.cantidad<=i.minStock).length;
const pctN=parseFloat(s.pct);const pctColor=pctN>=80?'#059669':pctN>=50?'#d97706':'#dc2626';
let h='';
h+='<div class="page-head"><div class="page-title"><h1>Dashboard</h1><p>Control Store Pro — ASSA ABLOY México · '+mes+'</p></div><span style="background:#f1f5f9;color:#64748b;font-size:11px;font-weight:700;padding:4px 10px;border-radius:20px;letter-spacing:.05em">v'+VERSION+'</span></div>';
// Alert banner
if(alertasStock>0||s.pendientes>0){h+='<div style="background:#fffbeb;border:1px solid #fbbf24;border-radius:var(--radius);padding:10px 16px;margin-bottom:16px;display:flex;align-items:center;gap:16px;flex-wrap:wrap">';if(alertasStock>0)h+='<span style="font-size:13px;color:#92400e"><i class="fas fa-exclamation-triangle mr-2"></i><strong>'+alertasStock+'</strong> artículo'+(alertasStock>1?'s':'')+' con stock bajo en almacén</span>';if(alertasStock>0&&s.pendientes>0)h+='<span style="color:#d1d5db;font-size:18px">·</span>';if(s.pendientes>0)h+='<span style="font-size:13px;color:#92400e"><i class="fas fa-clock mr-2"></i><strong>'+s.pendientes+'</strong> empleado'+(s.pendientes>1?'s':'')+' sin captura de tallas</span>';h+='</div>';}
// KPIs
h+='<div class="kpi-grid">';
h+='<div class="kpi" style="border-top:3px solid #2563eb"><div class="kpi-label"><i class="fas fa-users mr-1" style="color:#2563eb"></i>Empleados</div><div class="kpi-value">'+s.total+'</div><div class="kpi-sub">'+s.activos+' activos · '+s.bajas+' bajas</div></div>';
h+='<div class="kpi" style="border-top:3px solid '+pctColor+'"><div class="kpi-label"><i class="fas fa-clipboard-check mr-1" style="color:'+pctColor+'"></i>Captura de Tallas</div><div class="kpi-value" style="color:'+pctColor+'">'+s.pct+'%</div><div class="kpi-sub">'+s.capturados+' listos · '+s.pendientes+' por capturar</div></div>';
h+='<div class="kpi" style="border-top:3px solid #004B87"><div class="kpi-label"><i class="fas fa-hand-holding mr-1" style="color:#004B87"></i>Entregas</div><div class="kpi-value" style="color:#004B87">'+totalEnt+'</div><div class="kpi-sub">'+(totalEnt?Math.round(entConFirma/totalEnt*100):0)+'% con firma · '+entConFirma+' firmadas</div></div>';
if(gastoTotal>0){h+='<div class="kpi" style="border-top:3px solid #059669"><div class="kpi-label"><i class="fas fa-dollar-sign mr-1" style="color:#059669"></i>Inversión Total</div><div class="kpi-value" style="color:#059669;font-size:20px">'+fmtMoney(gastoTotal)+'</div><div class="kpi-sub">Uniformes + Almacén</div></div>';}
h+='<div class="kpi" style="border-top:3px solid '+(alertasStock>0?'#d97706':'#7c3aed')+'"><div class="kpi-label"><i class="fas '+(alertasStock>0?'fa-exclamation-triangle':'fa-user-slash')+' mr-1" style="color:'+(alertasStock>0?'#d97706':'#7c3aed')+'"></i>'+(alertasStock>0?'Stock Bajo':'Inactivos')+'</div><div class="kpi-value" style="color:'+(alertasStock>0?'#d97706':'#7c3aed')+'">'+(alertasStock>0?alertasStock:s.bajas)+'</div><div class="kpi-sub">'+(alertasStock>0?'artículos bajo mínimo':'no requieren captura')+'</div></div>';
h+='</div>';
// Área cards + doughnut
h+='<div style="display:grid;grid-template-columns:minmax(0,2fr) minmax(220px,1fr);gap:12px;margin-bottom:20px">';
h+='<div class="card"><div class="card-head"><h3><i class="fas fa-layer-group mr-2" style="color:#004B87"></i>Estado por Área</h3><span class="text-xs text-muted">Captura de tallas 2026</span></div>';
h+='<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(185px,1fr));gap:8px;padding:4px 16px 16px">';
areas.forEach(a=>{const st2=calcStatsArea(a);const p=parseInt(st2.pct,10);const bc=p>=80?'#059669':p>=50?'#d97706':'#dc2626';const bg=p>=80?'rgba(5,150,105,.06)':p>=50?'rgba(217,119,6,.06)':'rgba(220,38,38,.06)';const ai=areaIcon(a);h+='<div style="padding:12px;border-radius:8px;border:1px solid var(--border);background:'+bg+'"><div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><div style="width:34px;height:34px;border-radius:8px;background:'+ai.color+';display:flex;align-items:center;justify-content:center;flex-shrink:0"><i class="fas '+ai.icon+'" style="color:#fff;font-size:14px"></i></div><div style="flex:1;min-width:0"><p style="font-weight:700;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin:0">'+a+'</p><p style="font-size:11px;color:var(--text-muted);margin:0">'+st2.total+' empleado'+(st2.total!==1?'s':'')+'</p></div></div><div style="display:flex;justify-content:space-between;align-items:center;font-size:11px;margin-bottom:4px"><span style="color:var(--success)"><i class="fas fa-check mr-1"></i>'+st2.capturados+' listos</span><span style="font-weight:800;color:'+bc+'">'+p+'%</span></div><div style="height:5px;background:var(--border);border-radius:999px;overflow:hidden"><div style="height:100%;width:'+p+'%;background:'+bc+';border-radius:999px;transition:width .5s ease"></div></div></div>';});
h+='</div></div>';
// Doughnut
h+='<div class="chart-box" style="display:flex;flex-direction:column"><div class="card-head" style="padding-bottom:8px"><h3><i class="fas fa-chart-pie mr-2" style="color:#059669"></i>Estado de Captura</h3></div><div style="flex:1;min-height:160px"><canvas id="chEstado"></canvas></div><div style="margin-top:16px;border-top:1px solid var(--border);padding-top:12px">';
h+='<div style="display:flex;justify-content:space-between;align-items:center;padding:5px 0"><div style="display:flex;align-items:center;gap:8px"><span style="width:10px;height:10px;border-radius:50%;background:#059669;display:inline-block"></span><span style="font-size:12px">Capturados</span></div><strong style="color:#059669;font-size:14px">'+s.capturados+'</strong></div>';
h+='<div style="display:flex;justify-content:space-between;align-items:center;padding:5px 0"><div style="display:flex;align-items:center;gap:8px"><span style="width:10px;height:10px;border-radius:50%;background:#d97706;display:inline-block"></span><span style="font-size:12px">Pendientes</span></div><strong style="color:#d97706;font-size:14px">'+s.pendientes+'</strong></div>';
h+='<div style="display:flex;justify-content:space-between;align-items:center;padding:5px 0"><div style="display:flex;align-items:center;gap:8px"><span style="width:10px;height:10px;border-radius:50%;background:#2563eb;display:inline-block"></span><span style="font-size:12px">Bajas / Mov.</span></div><strong style="color:#2563eb;font-size:14px">'+s.bajas+'</strong></div>';
h+='</div></div>';
h+='</div>';
// Delivery section
if(totalEnt>0){h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:20px"><div class="chart-box"><div class="card-head"><h3><i class="fas fa-boxes mr-2" style="color:#d97706"></i>Tipo de Entregas</h3></div><canvas id="chEntregas" height="180"></canvas></div><div class="chart-box"><div class="card-head"><h3><i class="fas fa-history mr-2" style="color:#7c3aed"></i>Últimas Entregas</h3></div><div id="lastEntregas" style="padding:2px 0"></div></div></div>';}
// Detail table
h+='<div class="card"><div class="card-head"><h3><i class="fas fa-table mr-2" style="color:#004B87"></i>Detalle por Área</h3><span class="text-xs text-muted">Temporada 2026</span></div><div class="table-wrap"><table class="dt"><thead><tr><th>Área</th><th style="text-align:center">Total</th><th style="text-align:center">Capturados</th><th style="text-align:center">Pendientes</th><th style="text-align:center">Bajas</th><th>Progreso</th></tr></thead><tbody>';
areas.forEach(a=>{const st2=calcStatsArea(a);const p=parseInt(st2.pct,10);const bc=p>=80?'var(--success)':p>=50?'var(--warning)':'var(--danger)';h+='<tr><td>'+buildAreaBadge(a)+'</td><td style="text-align:center;font-weight:700">'+st2.total+'</td><td style="text-align:center;color:var(--success);font-weight:700">'+st2.capturados+'</td><td style="text-align:center;color:var(--warning)">'+st2.pendientes+'</td><td style="text-align:center;color:var(--info)">'+st2.bajas+'</td><td style="min-width:160px"><div class="flex items-center gap-2"><div class="progress" style="flex:1;height:8px"><div class="progress-bar" style="width:'+st2.pct+'%;background:'+bc+'"></div></div><span class="text-xs font-bold" style="color:'+bc+';min-width:36px">'+st2.pct+'%</span></div></td></tr>';});
h+='</tbody></table></div></div>';
return h;}
export function init(){
const st=getStore();const s=calcStats();
createChart('chEstado',{type:'doughnut',data:{labels:['Capturados','Pendientes','Bajas'],datasets:[{data:[s.capturados,s.pendientes,s.bajas],backgroundColor:['#059669','#d97706','#2563eb'],borderWidth:3,borderColor:'var(--surface)',hoverOffset:8}]},options:{responsive:true,maintainAspectRatio:false,cutout:'65%',plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>ctx.label+': '+ctx.parsed}}}}});
const da=st.entregas.filter(e=>e.tipo==='DOTACION_ANUAL').length;const ni=st.entregas.filter(e=>e.tipo==='NUEVO_INGRESO').length;const su=st.entregas.filter(e=>e.tipo==='SUSTITUCION').length;
if(da+ni+su>0){createChart('chEntregas',{type:'bar',data:{labels:['Dotación Anual','Nuevo Ingreso','Sustitución'],datasets:[{data:[da,ni,su],backgroundColor:['#059669','#2563eb','#d97706'],borderRadius:8,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0,color:'#94a3b8'},grid:{color:'rgba(0,0,0,.06)'}},x:{ticks:{color:'#64748b'},grid:{display:false}}}}});
const lb=document.getElementById('lastEntregas');if(lb){const TIPOS={DOTACION_ANUAL:{c:'#059669',l:'Dotación'},NUEVO_INGRESO:{c:'#2563eb',l:'Nuevo'},SUSTITUCION:{c:'#d97706',l:'Sustitución'}};lb.innerHTML=st.entregas.slice(-6).reverse().map(ent=>{const emp=st.employees.find(x=>x.id===ent.empleadoId);const nom=emp?emp.nombre+' '+(emp.paterno||''):ent.empleadoId;const ti=TIPOS[ent.tipo]||{c:'#6b7280',l:ent.tipo};const pc=(ent.prendas||[]).length;return'<div style="display:flex;align-items:center;gap:8px;padding:7px 0;border-bottom:1px solid var(--border)"><span style="background:'+ti.c+';color:#fff;font-size:10px;font-weight:700;padding:2px 7px;border-radius:20px;white-space:nowrap">'+ti.l+'</span><span style="font-weight:600;font-size:12px;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+nom+'</span><span style="font-size:11px;color:var(--text-muted);white-space:nowrap">'+pc+' pzs'+(ent.firma?' ✓':'')+'</span></div>';}).join('')||'<p class="text-sm text-muted">Sin entregas</p>';}}
}
