import{VERSION}from'./config.js';import{getStore}from'./storage.js';import{calcStats,calcStatsArea}from'./rules.js';import{buildAreaBadge,createChart}from'./ui.js';import{getAreaNames}from'./areas-config.js';
export function render(){const s=calcStats();const st=getStore();const totalEnt=st.entregas.length;const entConFirma=st.entregas.filter(e=>e.firma).length;const da=st.entregas.filter(e=>e.tipo==='DOTACION_ANUAL').length;const ni=st.entregas.filter(e=>e.tipo==='NUEVO_INGRESO').length;const su=st.entregas.filter(e=>e.tipo==='SUSTITUCION').length;const areas=getAreaNames();const now=new Date();const mes=now.toLocaleDateString('es-MX',{month:'long',year:'numeric'});let h='';
h+='<div class="page-head"><div class="page-title"><h1>Dashboard</h1><p>Control Store Pro — ASSA ABLOY México · '+mes+'</p></div><span class="topbar-badge" style="font-size:12px">v'+VERSION+'</span></div>';
h+='<div class="kpi-grid">';
h+='<div class="kpi" style="border-top:3px solid #2563eb"><div class="kpi-label"><i class="fas fa-users mr-1" style="color:#2563eb"></i>Total Empleados</div><div class="kpi-value">'+s.total+'</div><div class="kpi-sub">'+s.activos+' activos</div></div>';
h+='<div class="kpi" style="border-top:3px solid #059669"><div class="kpi-label"><i class="fas fa-check-circle mr-1" style="color:#059669"></i>Tallas Capturadas</div><div class="kpi-value" style="color:#059669">'+s.capturados+'</div><div class="kpi-sub">'+s.pct+'% completado</div></div>';
h+='<div class="kpi" style="border-top:3px solid #d97706"><div class="kpi-label"><i class="fas fa-clock mr-1" style="color:#d97706"></i>Pendientes</div><div class="kpi-value" style="color:#d97706">'+s.pendientes+'</div><div class="kpi-sub">'+(100-s.pct).toFixed(1)+'% restante</div></div>';
h+='<div class="kpi" style="border-top:3px solid #004B87"><div class="kpi-label"><i class="fas fa-hand-holding mr-1" style="color:#004B87"></i>Entregas Realizadas</div><div class="kpi-value" style="color:#004B87">'+totalEnt+'</div><div class="kpi-sub">'+(totalEnt?Math.round(entConFirma/totalEnt*100):0)+'% firmadas</div></div>';
h+='<div class="kpi" style="border-top:3px solid #7c3aed"><div class="kpi-label"><i class="fas fa-user-slash mr-1" style="color:#7c3aed"></i>Bajas / Inactivos</div><div class="kpi-value" style="color:#7c3aed">'+s.bajas+'</div><div class="kpi-sub">No requieren captura</div></div>';
h+='</div>';
h+='<div class="kpi-grid" style="grid-template-columns:repeat(auto-fill,minmax(160px,1fr));margin-bottom:20px">';
h+='<button class="btn btn-success" style="height:64px;font-size:15px;border-radius:10px;flex-direction:column;gap:4px;justify-content:center" id="dashNuevaEnt"><i class="fas fa-plus-circle" style="font-size:22px"></i>Nueva Entrega</button>';
h+='<button class="btn btn-primary" style="height:64px;font-size:15px;border-radius:10px;flex-direction:column;gap:4px;justify-content:center" id="dashEmpleados"><i class="fas fa-users" style="font-size:22px"></i>Empleados</button>';
h+='<button class="btn btn-ghost" style="height:64px;font-size:15px;border-radius:10px;flex-direction:column;gap:4px;justify-content:center" id="dashTotales"><i class="fas fa-calculator" style="font-size:22px"></i>Ver Totales</button>';
h+='<button class="btn btn-ghost" style="height:64px;font-size:15px;border-radius:10px;flex-direction:column;gap:4px;justify-content:center" id="dashExportar"><i class="fas fa-file-excel" style="font-size:22px"></i>Exportar</button>';
h+='</div>';
h+='<div class="chart-grid"><div class="chart-box"><div class="card-head"><h3><i class="fas fa-chart-bar mr-2" style="color:#004B87"></i>Empleados por Área</h3></div><canvas id="chAreas" height="200"></canvas></div><div class="chart-box"><div class="card-head"><h3><i class="fas fa-chart-pie mr-2" style="color:#059669"></i>Estado de Captura</h3></div><canvas id="chEstado" height="200"></canvas></div></div>';
if(totalEnt){h+='<div class="chart-grid" style="grid-template-columns:1fr 1fr"><div class="chart-box"><div class="card-head"><h3><i class="fas fa-boxes mr-2" style="color:#d97706"></i>Tipo de Entregas</h3></div><canvas id="chEntregas" height="200"></canvas></div><div class="chart-box"><div class="card-head"><h3><i class="fas fa-pen-fancy mr-2" style="color:#7c3aed"></i>Últimas Entregas</h3></div><div id="lastEntregas" style="padding:8px 0"></div></div></div>';}
h+='<div class="card"><div class="card-head"><h3><i class="fas fa-table mr-2" style="color:#004B87"></i>Progreso por Área</h3><span class="text-xs text-muted">Captura de tallas 2026</span></div><div class="table-wrap"><table class="dt"><thead><tr><th>Área</th><th style="text-align:center">Total</th><th style="text-align:center">Capturados</th><th style="text-align:center">Pendientes</th><th style="text-align:center">Bajas</th><th>Progreso</th></tr></thead><tbody>';
areas.forEach(a=>{const st2=calcStatsArea(a);const p=parseInt(st2.pct,10);const bc=p>=80?'var(--success)':p>=50?'var(--warning)':'var(--danger)';h+='<tr><td>'+buildAreaBadge(a)+'</td><td style="text-align:center;font-weight:700">'+st2.total+'</td><td style="text-align:center;color:var(--success);font-weight:700">'+st2.capturados+'</td><td style="text-align:center;color:var(--warning)">'+st2.pendientes+'</td><td style="text-align:center;color:var(--info)">'+st2.bajas+'</td><td style="min-width:160px"><div class="flex items-center gap-2"><div class="progress" style="flex:1;height:8px"><div class="progress-bar" style="width:'+st2.pct+'%;background:'+bc+'"></div></div><span class="text-xs font-bold" style="color:'+bc+';min-width:36px">'+st2.pct+'%</span></div></td></tr>';});
h+='</tbody></table></div></div>';return h;}
export function init(){const areas=getAreaNames();const st=getStore();createChart('chAreas',{type:'bar',data:{labels:areas.map(a=>a.length>10?a.substring(0,10)+'…':a),datasets:[{data:areas.map(a=>st.employees.filter(e=>e.area===a).length),backgroundColor:'#004B87',borderRadius:6,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0,color:'#94a3b8'},grid:{color:'rgba(0,0,0,.06)'}},x:{ticks:{color:'#64748b',font:{size:11}},grid:{display:false}}}}});const s=calcStats();createChart('chEstado',{type:'doughnut',data:{labels:['Capturados','Pendientes','Bajas / Mov'],datasets:[{data:[s.capturados,s.pendientes,s.bajas],backgroundColor:['#059669','#d97706','#2563eb'],borderWidth:3,borderColor:'#fff',hoverOffset:8}]},options:{responsive:true,maintainAspectRatio:false,cutout:'60%',plugins:{legend:{position:'bottom',labels:{padding:16,usePointStyle:true,font:{size:12,weight:'600'},color:'#374151'}}}}});const da=st.entregas.filter(e=>e.tipo==='DOTACION_ANUAL').length;const ni=st.entregas.filter(e=>e.tipo==='NUEVO_INGRESO').length;const su=st.entregas.filter(e=>e.tipo==='SUSTITUCION').length;if(da+ni+su>0){createChart('chEntregas',{type:'bar',data:{labels:['Dotación Anual','Nuevo Ingreso','Sustitución'],datasets:[{data:[da,ni,su],backgroundColor:['#059669','#2563eb','#d97706'],borderRadius:8,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0,color:'#94a3b8'},grid:{color:'rgba(0,0,0,.06)'}},x:{ticks:{color:'#64748b'},grid:{display:false}}}}});const lastBox=document.getElementById('lastEntregas');if(lastBox){const last=st.entregas.slice(-5).reverse();const TIPOS={DOTACION_ANUAL:{c:'#059669',l:'Dotación'},NUEVO_INGRESO:{c:'#2563eb',l:'Nuevo'},SUSTITUCION:{c:'#d97706',l:'Sustitución'}};lastBox.innerHTML=last.map(ent=>{const emp=st.employees.find(x=>x.id===ent.empleadoId);const nom=emp?emp.nombre+' '+(emp.paterno||''):ent.empleadoId;const ti=TIPOS[ent.tipo]||{c:'#6b7280',l:ent.tipo};const pc=(ent.prendas||[]).length;return'<div style="display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid var(--border)"><span style="background:'+ti.c+';color:#fff;font-size:10px;font-weight:700;padding:2px 8px;border-radius:20px;white-space:nowrap">'+ti.l+'</span><span style="font-weight:600;font-size:13px;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+nom+'</span><span style="font-size:11px;color:var(--text-muted);white-space:nowrap">'+pc+' pzs'+(ent.firma?' ✓':'')+'</span></div>';}).join('')||'<p class="text-sm text-muted">Sin entregas recientes</p>';}};}
document.getElementById('dashNuevaEnt')?.addEventListener('click',()=>{window.location.hash='entregas';window.dispatchEvent(new PopStateEvent('popstate',{state:{v:'entregas'}}));setTimeout(()=>document.getElementById('entNew')?.click(),300);});
document.getElementById('dashEmpleados')?.addEventListener('click',()=>{window.location.hash='empleados';window.dispatchEvent(new PopStateEvent('popstate',{state:{v:'empleados'}}));});
document.getElementById('dashTotales')?.addEventListener('click',()=>{window.location.hash='totales';window.dispatchEvent(new PopStateEvent('popstate',{state:{v:'totales'}}));});
document.getElementById('dashExportar')?.addEventListener('click',()=>{window.location.hash='exportar';window.dispatchEvent(new PopStateEvent('popstate',{state:{v:'exportar'}}));});}
