import{getStore,saveEntregas,log}from'./storage.js';import{esc,fmtDate,today}from'./utils.js';import{buildAreaBadge,notify,modal}from'./ui.js';import{initSignatureCapture,getSignatureData}from'./signature-capture.js';import{getUser,getUserRole}from'./user-roles.js';
const TIPOS={DOTACION_ANUAL:{label:'Dotación Anual',color:'#059669',bg:'#d1fae5',icon:'fa-boxes'},NUEVO_INGRESO:{label:'Nuevo Ingreso',color:'#2563eb',bg:'#dbeafe',icon:'fa-user-plus'},SUSTITUCION:{label:'Sustitución',color:'#d97706',bg:'#fef3c7',icon:'fa-exchange-alt'}};
function badgeTipo(t,custom){if(t==='OTRO')return'<span style="background:#f3f4f6;color:#6b7280;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;white-space:nowrap"><i class="fas fa-tag mr-1"></i>'+esc(custom||'Otro')+'</span>';const x=TIPOS[t]||{label:t||'—',color:'#6b7280',bg:'#f3f4f6',icon:'fa-tag'};return'<span style="background:'+x.bg+';color:'+x.color+';padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;white-space:nowrap"><i class="fas '+x.icon+' mr-1"></i>'+x.label+'</span>';}
export function render(){const s=getStore();const tot=s.entregas.length;const da=s.entregas.filter(e=>e.tipo==='DOTACION_ANUAL').length;const ni=s.entregas.filter(e=>e.tipo==='NUEVO_INGRESO').length;const su=s.entregas.filter(e=>e.tipo==='SUSTITUCION').length;const cf=s.entregas.filter(e=>e.firma).length;let h='<div class="page-head"><div class="page-title"><h1>Entregas de Uniformes</h1><p>Dotación anual · Nuevos ingresos · Sustituciones</p></div></div>';h+='<div class="kpi-grid"><div class="kpi"><div class="kpi-label">Total Entregas</div><div class="kpi-value">'+tot+'</div></div><div class="kpi success"><div class="kpi-label">Dotación Anual</div><div class="kpi-value">'+da+'</div><div class="kpi-sub">'+TIPOS.DOTACION_ANUAL.label+'</div></div><div class="kpi info"><div class="kpi-label">Nuevo Ingreso</div><div class="kpi-value">'+ni+'</div><div class="kpi-sub">'+TIPOS.NUEVO_INGRESO.label+'</div></div><div class="kpi warning"><div class="kpi-label">Sustituciones</div><div class="kpi-value">'+su+'</div><div class="kpi-sub">Reposición</div></div><div class="kpi"><div class="kpi-label">Con Firma</div><div class="kpi-value">'+cf+'</div><div class="kpi-sub">'+(tot?Math.round(cf/tot*100):0)+'% firmadas</div></div></div>';h+='<div class="card mb-4"><div class="card-body"><div class="form-row c4"><div><label class="form-label">Tipo</label><select class="form-select" id="entFT"><option value="">Todos los tipos</option>'+Object.entries(TIPOS).map(([k,v])=>'<option value="'+k+'">'+v.label+'</option>').join('')+'<option value="OTRO">Otro</option></select></div><div><label class="form-label">Área</label><select class="form-select" id="entFA"><option value="">Todas las áreas</option>'+[...new Set(s.employees.map(e=>e.area))].sort().map(a=>'<option>'+esc(a)+'</option>').join('')+'</select></div><div><label class="form-label">Buscar empleado</label><input class="form-input" id="entFS" placeholder="Nombre o número..."></div><div class="flex items-center" style="align-items:flex-end"><button class="btn btn-ghost" style="width:100%" id="entFClear"><i class="fas fa-times"></i> Limpiar</button></div></div></div></div>';h+='<div class="card"><div class="card-head"><h3>Historial de Entregas</h3><span class="text-sm text-muted" id="entCount"></span></div><div class="table-wrap"><table class="dt"><thead><tr><th>Fecha</th><th>Empleado</th><th>Área</th><th>Tipo</th><th style="text-align:center">Prendas</th><th style="text-align:center">Firma</th><th>Obs</th></tr></thead><tbody id="entTB"></tbody></table></div></div>';return h;}
function renderRows(){const s=getStore();const ft=document.getElementById('entFT')?.value||'';const fa=document.getElementById('entFA')?.value||'';const fs=(document.getElementById('entFS')?.value||'').toLowerCase();let list=s.entregas.slice().reverse();if(ft)list=list.filter(e=>e.tipo===ft);if(fa){list=list.filter(e=>{const eA=e.area||(s.employees.find(x=>x.id===e.empleadoId)?.area)||'';return eA===fa;});}if(fs){list=list.filter(e=>{const emp=s.employees.find(x=>x.id===e.empleadoId);const nom=emp?(emp.nombre+' '+(emp.paterno||'')).toLowerCase():'';return nom.includes(fs)||(e.empleadoId||'').includes(fs);});}const tb=document.getElementById('entTB');if(!tb)return;const cc=document.getElementById('entCount');if(cc)cc.textContent=list.length+' registros';if(!list.length){tb.innerHTML='<tr><td colspan="7" class="empty-state"><i class="fas fa-hand-holding"></i><p>Sin entregas registradas</p></td></tr>';return;}tb.innerHTML=list.map(ent=>{const emp=s.employees.find(x=>x.id===ent.empleadoId);const nom=emp?esc(emp.nombre+' '+(emp.paterno||'')):ent.empleadoId;const areaStr=ent.area||emp?.area||'';const area=areaStr?buildAreaBadge(areaStr):'—';const pc=(ent.prendas||[]).length;const firma=ent.firma?'<img src="'+ent.firma+'" style="height:30px;max-width:90px;object-fit:contain;border:1px solid var(--border);border-radius:4px;cursor:pointer" class="sig-preview" data-id="'+ent.id+'" title="Ver firma">':'<span style="color:var(--text-muted);font-size:12px">—</span>';return'<tr><td class="text-xs font-mono">'+fmtDate(ent.fecha)+'</td><td class="font-bold">'+nom+'</td><td>'+area+'</td><td>'+badgeTipo(ent.tipo,ent.tipoCustom)+'</td><td style="text-align:center"><span class="badge badge-info">'+pc+' pzs</span></td><td style="text-align:center">'+firma+'</td><td class="text-xs text-sec" style="max-width:120px">'+esc(ent.observaciones||'—')+'</td></tr>';}).join('');}
function showEmpCard(emp){const card=document.getElementById('entEmpCard');if(!card)return;if(!emp){card.innerHTML='';return;}const colors=['#004B87','#16a34a','#ca8a04','#7c3aed','#dc2626'];const ci=Math.abs((emp.id||'').split('').reduce((a,c)=>a+c.charCodeAt(0),0))%colors.length;const av=emp.foto?'<img src="'+emp.foto+'" style="width:100%;height:100%;object-fit:cover">':'<span style="font-size:22px;font-weight:700;color:#fff">'+((emp.nombre||'?')[0]).toUpperCase()+'</span>';const nTallas=Object.values(emp.tallas||{}).filter(Boolean).length;card.innerHTML='<div style="display:flex;align-items:center;gap:14px;padding:12px 16px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);margin-bottom:4px"><div style="width:52px;height:52px;border-radius:50%;background:'+colors[ci]+';display:flex;align-items:center;justify-content:center;flex-shrink:0;overflow:hidden">'+av+'</div><div style="flex:1;min-width:0"><p style="font-weight:700;font-size:15px;margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(emp.nombre+' '+(emp.paterno||''))+'</p><p style="font-size:12px;color:var(--text-muted);margin:0">'+esc(emp.area)+' · Empleado #'+esc(emp.id)+' · '+nTallas+' talla'+(nTallas!==1?'s':'')+' capturada'+(nTallas!==1?'s':'')+'</p></div><span class="badge badge-'+(emp.estado==='activo'?'success':'neutral')+'">'+emp.estado.toUpperCase()+'</span></div>';}
function loadPrendas(emp){const box=document.getElementById('entPB');if(!box)return;if(!emp){box.innerHTML='';return;}const entries=Object.entries(emp.tallas||{}).filter(p=>p[1]);if(!entries.length){box.innerHTML='<div style="background:var(--warning-light);border:1px solid var(--warning);border-radius:8px;padding:12px 16px"><i class="fas fa-exclamation-triangle mr-2" style="color:var(--warning)"></i><span class="text-sm">Sin tallas capturadas — se puede registrar la entrega pero sin detalle de tallas</span></div>';return;}box.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><label class="form-label" style="margin:0">Prendas a entregar — desactiva las que NO se entregan esta vez:</label><span class="badge badge-info">'+entries.length+' prendas</span></div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px">'+entries.map(p=>'<label style="display:flex;align-items:center;gap:10px;padding:14px;border-radius:var(--radius);cursor:pointer;border:2px solid var(--border);background:var(--surface-2);min-height:64px;transition:border-color .15s"><input type="checkbox" value="'+esc(p[0])+'" class="entC" checked style="width:22px;height:22px;flex-shrink:0;accent-color:#004B87;cursor:pointer"><div style="flex:1;min-width:0"><p style="font-weight:700;font-size:13px;margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(p[0])+'</p><p style="font-size:12px;color:var(--text-muted);margin:0">Talla: <strong>'+esc(p[1])+'</strong></p></div></label>').join('')+'</div>';}
function newEntrega(){
  const act=getStore().employees.filter(e=>e.estado==='activo');
  let h='<div class="form-row c2 mb-4">';
  // Búsqueda de empleado
  h+='<div class="form-group" style="position:relative"><label class="form-label">Empleado *</label>';
  h+='<input class="form-input" id="entESearch" placeholder="Escribe nombre o número de empleado..." autocomplete="off">';
  h+='<input type="hidden" id="entE" value="">';
  h+='<div id="entEDrop" style="display:none;position:absolute;left:0;right:0;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);box-shadow:0 8px 24px rgba(0,0,0,.18);z-index:300;max-height:230px;overflow-y:auto;top:calc(100% + 2px)"></div>';
  h+='</div>';
  // Tipo de entrega
  h+='<div class="form-group"><label class="form-label">Tipo de Entrega *</label>';
  h+='<select class="form-select" id="entT"><option value="">— Seleccionar —</option>';
  h+=Object.entries(TIPOS).map(([k,v])=>'<option value="'+k+'">'+v.label+'</option>').join('');
  h+='<option value="OTRO">Otro...</option></select>';
  h+='<input class="form-input mt-2" id="entTOtro" placeholder="Describe el tipo de entrega..." style="display:none">';
  h+='</div></div>';
  // Campaña + Fecha
  const camps=(getStore().campanias||[]).filter(c=>c.estado==='activa'||c.estado==='planificacion');
  h+='<div class="form-row c3 mb-4">';
  h+='<div class="form-group"><label class="form-label">Área</label><input class="form-input" id="entArea" placeholder="Se llena al seleccionar empleado"></div>';
  h+='<div class="form-group"><label class="form-label">Campaña</label><select class="form-select" id="entCamp"><option value="">— Sin campaña —</option>'+camps.map(c=>'<option value="'+c.id+'">'+esc(c.nombre)+'</option>').join('')+'</select></div>';
  h+='<div class="form-group"><label class="form-label">Fecha</label><input type="date" class="form-input" id="entF" value="'+today()+'"></div>';
  h+='</div>';
  // Tarjeta empleado
  h+='<div id="entEmpCard" class="mb-3"></div>';
  // Prendas
  h+='<div id="entPB" class="mb-4"></div>';
  // Firma
  h+='<div class="mb-4"><label class="form-label" style="font-size:13px;margin-bottom:8px"><i class="fas fa-pen-fancy mr-1"></i>Firma del empleado — dibuja con el dedo en el área blanca</label><div id="sigContainer"></div><p class="text-xs text-muted mt-2"><i class="fas fa-info-circle mr-1"></i>La firma queda guardada como evidencia de la entrega</p></div>';
  // Obs
  h+='<div class="form-group"><label class="form-label">Observaciones</label><textarea class="form-input" id="entO" rows="2" placeholder="Notas opcionales..."></textarea></div>';
  modal.open('Registrar Entrega',h,'<button class="btn btn-ghost" id="mCancel">Cancelar</button><button class="btn btn-success" id="mSaveEnt"><i class="fas fa-check"></i> Confirmar Entrega</button>','xl');
  setTimeout(()=>initSignatureCapture('sigContainer'),300);
  document.getElementById('mCancel')?.addEventListener('click',()=>modal.close());
  document.getElementById('mSaveEnt')?.addEventListener('click',saveEntrega);
  // Tipo OTRO toggle
  document.getElementById('entT')?.addEventListener('change',function(){const b=document.getElementById('entTOtro');if(b)b.style.display=this.value==='OTRO'?'':'none';});
  // Búsqueda en vivo
  const srch=document.getElementById('entESearch');const drop=document.getElementById('entEDrop');
  function doSearch(q){
    const ql=q.toLowerCase().trim();
    if(!ql){drop.style.display='none';return;}
    const res=act.filter(e=>{const n=((e.nombre||'')+' '+(e.paterno||'')+' '+(e.materno||'')).toLowerCase();return n.includes(ql)||(e.id||'').toLowerCase().includes(ql);}).slice(0,15);
    if(!res.length){drop.innerHTML='<div style="padding:12px 16px;font-size:13px;color:var(--text-muted)">Sin resultados para "'+esc(q)+'"</div>';drop.style.display='block';return;}
    drop.innerHTML=res.map(e=>'<div class="eRes" data-id="'+e.id+'" style="padding:10px 14px;cursor:pointer;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:10px"><div style="flex:1;min-width:0"><p style="font-weight:700;font-size:13px;margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(e.nombre+' '+(e.paterno||''))+'</p><p style="font-size:11px;color:var(--text-muted);margin:0">Empleado #'+esc(e.id)+' · '+esc(e.area)+'</p></div><span class="badge badge-'+(e.estado==='activo'?'success':'neutral')+'" style="font-size:10px">'+esc(e.id)+'</span></div>').join('');
    drop.style.display='block';
  }
  srch?.addEventListener('input',function(){doSearch(this.value);});
  srch?.addEventListener('focus',function(){if(this.value)doSearch(this.value);});
  srch?.addEventListener('blur',()=>{setTimeout(()=>{if(drop)drop.style.display='none';},160);});
  drop?.addEventListener('mousedown',e=>e.preventDefault());
  drop?.addEventListener('click',function(e){
    const item=e.target.closest('.eRes');if(!item)return;
    const empId=item.dataset.id;const emp=act.find(x=>x.id===empId);if(!emp)return;
    document.getElementById('entE').value=empId;
    srch.value=emp.nombre+' '+(emp.paterno||'')+' (#'+emp.id+')';
    drop.style.display='none';
    const aI=document.getElementById('entArea');if(aI)aI.value=emp.area||'';
    loadPrendas(emp);showEmpCard(emp);
  });
  drop?.addEventListener('mouseover',function(e){const item=e.target.closest('.eRes');this.querySelectorAll('.eRes').forEach(el=>el.style.background='');if(item)item.style.background='var(--surface-2)';});
  drop?.addEventListener('mouseout',function(){this.querySelectorAll('.eRes').forEach(el=>el.style.background='');});
}
function saveEntrega(){const empId=document.getElementById('entE')?.value;const tipo=document.getElementById('entT')?.value;if(!empId){notify('Busca y selecciona un empleado','warning');return;}if(!tipo){notify('Selecciona el tipo de entrega','warning');return;}const tipoCustom=tipo==='OTRO'?(document.getElementById('entTOtro')?.value||'').trim():'';if(tipo==='OTRO'&&!tipoCustom){notify('Describe el tipo de entrega','warning');return;}const emp=getStore().employees.find(e=>e.id===empId);const area=document.getElementById('entArea')?.value||emp?.area||'';const prendas=Array.from(document.querySelectorAll('.entC:checked')).map(c=>({prenda:c.value,talla:emp?.tallas?.[c.value]||''}));const firma=getSignatureData();const usuario=getUser();const campaniaId=document.getElementById('entCamp')?.value||'';const ent={id:Date.now().toString(),empleadoId:empId,tipo,tipoCustom,area,fecha:document.getElementById('entF')?.value||today(),prendas,firma:firma||null,observaciones:document.getElementById('entO')?.value||'',campaniaId,registradoPor:usuario?.name||'Sistema',registradoPorId:usuario?.id||''};getStore().entregas.push(ent);saveEntregas();log('ENTREGA_'+tipo,(prendas.length||0)+' prendas — emp#'+empId+(firma?' CON FIRMA':''));modal.close();notify('Entrega registrada'+(firma?' ✓ con firma':''),'success');renderRows();}
function viewSig(id){const ent=getStore().entregas.find(e=>e.id===id);if(!ent||!ent.firma)return;const emp=getStore().employees.find(x=>x.id===ent.empleadoId);modal.open('Firma — '+(emp?emp.nombre+' '+(emp.paterno||''):ent.empleadoId),'<div style="text-align:center;padding:16px"><img src="'+ent.firma+'" style="max-width:100%;border:1px solid var(--border);border-radius:8px"><p class="text-xs text-muted mt-2">Fecha: '+fmtDate(ent.fecha)+' · '+badgeTipo(ent.tipo,ent.tipoCustom)+'</p></div>','<button class="btn btn-ghost" id="mCancel">Cerrar</button>');document.getElementById('mCancel')?.addEventListener('click',()=>modal.close());}
function attachEvents(){const ta=document.getElementById('topbarActions');if(ta){ta.innerHTML='<button class="btn btn-success topbar-action-btn" id="btnTopNuevaEnt"><i class="fas fa-plus"></i> Nueva Entrega</button>';document.getElementById('btnTopNuevaEnt')?.addEventListener('click',newEntrega);}document.getElementById('entNew')?.addEventListener('click',newEntrega);['entFT','entFA'].forEach(id=>document.getElementById(id)?.addEventListener('change',renderRows));document.getElementById('entFS')?.addEventListener('input',renderRows);document.getElementById('entFClear')?.addEventListener('click',()=>{document.getElementById('entFT').value='';document.getElementById('entFA').value='';document.getElementById('entFS').value='';renderRows();});document.getElementById('entTB')?.addEventListener('click',e=>{const sp=e.target.closest('.sig-preview');if(sp)viewSig(sp.dataset.id);});}
export function init(){attachEvents();renderRows();}
