import{getStore}from'./storage.js';import{verificarCaptura,calcTotalesDetallados}from'./rules.js';import{notify}from'./ui.js';
function renderCards(){let h='<div class="page-head"><div class="page-title"><h1>Exportar Datos</h1><p>Descarga en formato Excel</p></div></div>';h+='<div class="grid-3">';h+='<div class="card"><div class="card-body text-center" style="padding:32px"><i class="fas fa-users" style="font-size:36px;color:var(--accent);margin-bottom:12px;display:block"></i><h3 class="mb-3">Empleados</h3><p class="text-sm text-sec mb-4">Lista completa con tallas</p><button class="btn btn-accent exp-emp"><i class="fas fa-download"></i> Descargar</button></div></div>';h+='<div class="card"><div class="card-body text-center" style="padding:32px"><i class="fas fa-calculator" style="font-size:36px;color:var(--success);margin-bottom:12px;display:block"></i><h3 class="mb-3">Totales</h3><p class="text-sm text-sec mb-4">Por prenda y talla</p><button class="btn btn-success exp-tot"><i class="fas fa-download"></i> Descargar</button></div></div>';h+='<div class="card"><div class="card-body text-center" style="padding:32px"><i class="fas fa-hand-holding" style="font-size:36px;color:var(--warning);margin-bottom:12px;display:block"></i><h3 class="mb-3">Entregas</h3><p class="text-sm text-sec mb-4">Historial completo</p><button class="btn btn-warning exp-ent"><i class="fas fa-download"></i> Descargar</button></div></div>';h+='<div class="card"><div class="card-body text-center" style="padding:32px"><i class="fas fa-truck" style="font-size:36px;color:var(--primary);margin-bottom:12px;display:block"></i><h3 class="mb-3">Proveedores</h3><p class="text-sm text-sec mb-4">Compras y costos</p><button class="btn btn-primary exp-prov"><i class="fas fa-download"></i> Descargar</button></div></div>';h+='<div class="card"><div class="card-body text-center" style="padding:32px"><i class="fas fa-history" style="font-size:36px;color:var(--danger);margin-bottom:12px;display:block"></i><h3 class="mb-3">Bitácora</h3><p class="text-sm text-sec mb-4">Registro de cambios</p><button class="btn btn-danger exp-log"><i class="fas fa-download"></i> Descargar</button></div></div>';h+='</div>';return h;}
export function render(){return renderCards();}
function downloadExcel(rows,sheetName,fileName){const ws=XLSX.utils.aoa_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheetName);XLSX.writeFile(wb,fileName);notify('Exportado: '+fileName,'success');}
function exportEmp(){const rows=[['ID','Nombre','Paterno','Materno','Area','Estado','Perfil','Capturado','Tallas']];getStore().employees.forEach(emp=>{const ts=Object.entries(emp.tallas||{}).filter(p=>p[1]).map(p=>p[0]+':'+p[1]).join(' | ');rows.push([emp.id,emp.nombre,emp.paterno||'',emp.materno||'',emp.area,emp.estado,emp.perfilDotacion||'AUTO',verificarCaptura(emp)?'SI':'NO',ts]);});downloadExcel(rows,'Empleados','Empleados_ASAABLOY.xlsx');}
function exportTot(){const det=calcTotalesDetallados();const rows=[['Prenda','Talla','Base','Stock','Total']];Object.entries(det).forEach(([p,tallas])=>{Object.entries(tallas).forEach(([t,o])=>{rows.push([p,t,o.base,o.stock,o.total]);});});downloadExcel(rows,'Totales','Totales_ASAABLOY.xlsx');}
function exportEnt(){const rows=[['Fecha','ID','Nombre','Tipo','Prendas','Obs']];getStore().entregas.forEach(ent=>{const emp=getStore().employees.find(x=>x.id===ent.empleadoId);const nom=emp?emp.nombre+' '+(emp.paterno||''):'';const prendas=(ent.prendas||[]).map(p=>p.prenda+':'+p.talla).join(' | ');rows.push([ent.fecha,ent.empleadoId,nom,ent.tipo,prendas,ent.observaciones||'']);});downloadExcel(rows,'Entregas','Entregas_ASAABLOY.xlsx');}
function exportProv(){const rows=[['Fecha','Proveedor','Prenda','Talla','Cant','P.Unit','Total','Ref','Obs']];getStore().proveedores.forEach(p=>{rows.push([p.fecha,p.proveedor,p.prenda,p.talla,p.cantidad,p.precioUnitario,p.cantidad*p.precioUnitario,p.referencia||'',p.observaciones||'']);});downloadExcel(rows,'Proveedores','Proveedores_ASAABLOY.xlsx');}
function exportLog(){const rows=[['Fecha','Accion','Detalle']];getStore().auditLog.forEach(l=>{rows.push([l.ts,l.action,l.det||'']);});downloadExcel(rows,'Bitacora','Bitacora_ASAABLOY.xlsx');}
function handleExportClick(e){if(e.target.closest('.exp-emp'))exportEmp();else if(e.target.closest('.exp-tot'))exportTot();else if(e.target.closest('.exp-ent'))exportEnt();else if(e.target.closest('.exp-prov'))exportProv();else if(e.target.closest('.exp-log'))exportLog();}
export function init(){const mc=document.getElementById('mainContent');if(!mc)return;mc.removeEventListener('click',handleExportClick);mc.addEventListener('click',handleExportClick);}
