import{TIPO_TALLA}from'./config.js';import{getStore,saveProveedores,saveComprasAlmacen,saveStockUniformes,saveInventario,log}from'./storage.js';import{esc,fmt,fmtMoney,fmtDate,today,getTallasOpts}from'./utils.js';import{notify,modal}from'./ui.js';
let currentTab='compras';
const PAGE_SIZE=50;
let comprasVisibleLimit=PAGE_SIZE;
function getCats(){try{return JSON.parse(localStorage.getItem('_cats_provs')||'[]');}catch{return[];}}
function normProv(v){return String(v||'').trim().toLowerCase();}
function getProvPhone(c){return c?.telefono||c?.tel||'';}
function getComprasLegacy(){return(getStore().proveedores||[]).filter(p=>p&&(p.cantidad!=null||p.prenda||p.precioUnitario!=null));}
function syncContactoEnCompras(cats){const s=getStore();let changed=false;(s.proveedores||[]).forEach(p=>{const c=cats.find(x=>normProv(x.nombre)===normProv(p.proveedor));if(!c)return;p.contacto=c.contacto||'';p.telefono=getProvPhone(c);p.email=c.email||'';p.notas_proveedor=c.notas||'';changed=true;});if(changed)saveProveedores();}
function saveCats(c){localStorage.setItem('_cats_provs',JSON.stringify(c));syncContactoEnCompras(c);}
function compraEntradaMonto(entrada,lineas){const total=lineas.reduce((sum,l)=>sum+(Number(l.costo_total)||((Number(l.cantidad)||0)*(Number(l.costo_unitario)||0))),0);return total||Number(entrada.factura_total)||0;}
function getHistorialProveedor(c){const s=getStore();const productos=s.productos||[];const lineas=s.lineasEntrada||[];const entradas=(s.entradas||[]).filter(e=>(e.proveedor_id&&e.proveedor_id===c.id)||normProv(e.proveedor)===normProv(c.nombre)).map(e=>{const detalle=lineas.filter(l=>l.entrada_id===e.id);return{...e,_lineas:detalle,_monto:compraEntradaMonto(e,detalle)};}).sort((a,b)=>new Date(b.fecha_hora||b.fecha||0)-new Date(a.fecha_hora||a.fecha||0));const productoIds=new Set();entradas.forEach(e=>e._lineas.forEach(l=>productoIds.add(l.producto_id)));const surtidos=productos.filter(p=>productoIds.has(p.id)||normProv(p.proveedor_frecuente)===normProv(c.nombre)||p.proveedor_frecuente===c.id);const y=new Date().getFullYear();const totalAnio=entradas.filter(e=>new Date(e.fecha_hora||e.fecha||0).getFullYear()===y).reduce((sum,e)=>sum+e._monto,0);const ultima=entradas[0]||null;return{entradas,surtidos,totalAnio,ultima};}
export function render(){let h='<div class="page-head"><div class="page-title"><h1>Proveedores</h1><p>Catálogo de proveedores y control de compras</p></div><div id="provHeaderBtn"></div></div>';h+='<div class="tabs mb-4"><button class="tab-btn active" data-tab="compras"><i class="fas fa-file-invoice-dollar mr-2"></i>Compras</button><button class="tab-btn" data-tab="catalogo"><i class="fas fa-address-book mr-2"></i>Catálogo de Proveedores</button></div>';h+='<div id="provTabContent"></div>';return h;}
function renderCompras(){const s=getStore();const compras=getComprasLegacy();const almList=s.comprasAlmacen||[];const totUnif=compras.reduce((sum,p)=>sum+(p.cantidad*p.precioUnitario),0);const totAlm=almList.reduce((sum,c)=>sum+(c.cantidad*c.precioUnitario),0);const totMXN=totUnif+totAlm;const totPiezas=compras.reduce((sum,p)=>sum+p.cantidad,0)+almList.reduce((sum,c)=>sum+c.cantidad,0);const provsList=[...new Set([...compras,...almList].map(p=>p.proveedor).filter(Boolean))];let h='<div class="kpi-grid"><div class="kpi success"><div class="kpi-label"><i class="fas fa-chart-line mr-1"></i>Gasto Total</div><div class="kpi-value">'+fmtMoney(totMXN)+'</div></div><div class="kpi info"><div class="kpi-label"><i class="fas fa-tshirt mr-1"></i>Uniformes</div><div class="kpi-value">'+fmtMoney(totUnif)+'</div></div><div class="kpi" style="border-top:3px solid #7c3aed"><div class="kpi-label"><i class="fas fa-boxes mr-1"></i>Almacén / Otros</div><div class="kpi-value" style="color:#7c3aed">'+fmtMoney(totAlm)+'</div></div><div class="kpi warning"><div class="kpi-label"><i class="fas fa-cubes mr-1"></i>Piezas</div><div class="kpi-value">'+fmt(totPiezas)+'</div></div><div class="kpi"><div class="kpi-label"><i class="fas fa-truck mr-1"></i>Proveedores</div><div class="kpi-value">'+provsList.length+'</div></div></div>';h+='<div class="card mb-4"><div class="card-body"><div class="form-row c3"><div><label class="form-label">Proveedor</label><select class="form-select" id="pvFP"><option value="">Todos</option>'+provsList.map(p=>'<option>'+esc(p)+'</option>').join('')+'</select></div><div><label class="form-label">Buscar artículo</label><input class="form-input" id="pvFS" placeholder="Nombre de artículo o prenda..."></div><div class="flex items-center" style="align-items:flex-end"><button class="btn btn-ghost" style="width:100%" id="pvFClear"><i class="fas fa-times"></i> Limpiar</button></div></div></div></div>';h+='<div class="card"><div class="card-head"><h3>Historial de Compras</h3><span class="text-sm text-muted" id="pvCount"></span></div><div class="table-wrap"><table class="dt"><thead><tr><th>Fecha</th><th>Tipo</th><th>Proveedor</th><th>Artículo / Prenda</th><th>Talla</th><th style="text-align:center">Cant</th><th style="text-align:right">P.U.</th><th style="text-align:right">Total</th><th>Ref / OC</th><th></th></tr></thead><tbody id="pvTB"></tbody></table></div><div class="text-center mt-2 mb-3"><button class="btn btn-ghost btn-sm" id="pvVerMas" style="display:none">Ver más</button></div></div>';document.getElementById('provTabContent').innerHTML=h;document.getElementById('provHeaderBtn').innerHTML='<button class="btn btn-success" id="provNewCompra"><i class="fas fa-plus"></i> Nueva Compra</button>';attachComprasEvents();renderComprasRows();}
function renderComprasRows(){const s=getStore();const fp=document.getElementById('pvFP')?.value||'';const fs=(document.getElementById('pvFS')?.value||'').toLowerCase();const unif=getComprasLegacy().map(p=>({...p,_tipo:'UNIF',_art:p.prenda,_talla:p.talla||'—'}));const alm=(s.comprasAlmacen||[]).map(c=>({...c,_tipo:'ALM',_art:c.articulo,_talla:'—'}));let list=[...unif,...alm].sort((a,b)=>(b.fecha||'').localeCompare(a.fecha||''));if(fp)list=list.filter(p=>p.proveedor===fp);if(fs)list=list.filter(p=>(p._art||'').toLowerCase().includes(fs));const tb=document.getElementById('pvTB');if(!tb)return;const cc=document.getElementById('pvCount');if(cc)cc.textContent=Math.min(comprasVisibleLimit,list.length)+' de '+list.length+' registros';if(!list.length){tb.innerHTML='<tr><td colspan="10" class="empty-state"><i class="fas fa-truck"></i><p>Sin compras registradas</p></td></tr>';return;}tb.innerHTML=list.slice(0,comprasVisibleLimit).map(p=>{const total=p.cantidad*p.precioUnitario;const badge=p._tipo==='UNIF'?'<span style="background:#dbeafe;color:#1d4ed8;font-size:10px;font-weight:700;padding:2px 8px;border-radius:20px">Uniforme</span>':'<span style="background:#ede9fe;color:#7c3aed;font-size:10px;font-weight:700;padding:2px 8px;border-radius:20px">Almacén</span>';const delBtn=p._tipo==='UNIF'?'<button class="btn btn-ghost btn-sm pv-del" data-id="'+p.id+'" style="color:var(--danger)"><i class="fas fa-trash"></i></button>':'<button class="btn btn-ghost btn-sm pv-del-alm" data-id="'+p.id+'" style="color:var(--danger)"><i class="fas fa-trash"></i></button>';return'<tr><td class="text-xs font-mono">'+fmtDate(p.fecha)+'</td><td>'+badge+'</td><td class="font-bold">'+esc(p.proveedor||'—')+'</td><td>'+esc(p._art)+'</td><td><span class="badge badge-neutral">'+esc(p._talla)+'</span></td><td style="text-align:center;font-weight:700">'+p.cantidad+'</td><td style="text-align:right">'+fmtMoney(p.precioUnitario)+'</td><td style="text-align:right;font-weight:700;color:var(--success)">'+fmtMoney(total)+'</td><td class="text-xs text-muted">'+esc(p.referencia||'—')+'</td><td>'+delBtn+'</td></tr>';}).join('');const more=document.getElementById('pvVerMas');if(more)more.style.display=list.length>comprasVisibleLimit?'inline-flex':'none';}
function openNuevaCompra(){const cats=getCats();const pl=Object.keys(TIPO_TALLA);let h='';
// Mode toggle
h+='<div style="display:flex;gap:8px;margin-bottom:20px"><button class="btn btn-success" id="pvModeUnif" style="flex:1"><i class="fas fa-tshirt mr-1"></i>Uniforme</button><button class="btn btn-ghost" id="pvModeOtro" style="flex:1"><i class="fas fa-box mr-1"></i>Otro Producto</button></div>';
// Proveedor + Fecha (común)
h+='<div class="form-row c2 mb-3"><div class="form-group"><label class="form-label">Proveedor *</label>';
if(cats.length){h+='<select class="form-select mb-1" id="pvP"><option value="">— Del catálogo —</option>'+cats.map(c=>'<option>'+esc(c.nombre)+'</option>').join('')+'</select><input class="form-input" id="pvPText" placeholder="O escribe uno nuevo...">';}
else{h+='<input class="form-input" id="pvPText" placeholder="Nombre del proveedor">';}
h+='</div><div class="form-group"><label class="form-label">Fecha</label><input type="date" class="form-input" id="pvF" value="'+today()+'"></div></div>';
// Uniforme fields
h+='<div id="pvUnifF"><div class="form-row c2 mb-3"><div class="form-group"><label class="form-label">Prenda *</label><select class="form-select" id="pvPr">'+pl.map(p=>'<option>'+p+'</option>').join('')+'</select></div><div class="form-group"><label class="form-label">Talla *</label><select class="form-select" id="pvT"></select></div></div></div>';
// Otro fields
h+='<div id="pvOtroF" style="display:none"><div class="form-row c2 mb-3"><div class="form-group"><label class="form-label">Artículo / Producto *</label><input class="form-input" id="pvArt" placeholder="Ej: Guantes de nitrilo, Aceite, Papel..."></div><div class="form-group"><label class="form-label">Categoría</label><input class="form-input" id="pvCatL" placeholder="Ej: Herramienta, Limpieza, Despensa..."></div></div></div>';
// Cantidad + Precio + Total
h+='<div class="form-row c3 mb-3"><div class="form-group"><label class="form-label">Cantidad *</label><input type="number" class="form-input" id="pvC" min="1" value="1"></div><div class="form-group"><label class="form-label">Precio Unitario (MXN) *</label><input type="number" class="form-input" id="pvPrU" min="0" step="0.01" placeholder="0.00"></div><div class="form-group"><label class="form-label">Total</label><input class="form-input" id="pvTot" readonly style="background:var(--surface-2);font-weight:700;color:var(--success)" value="$0.00"></div></div>';
h+='<div class="form-row c2 mb-3"><div class="form-group"><label class="form-label">Ref / OC</label><input class="form-input" id="pvR" placeholder="Orden de compra o referencia"></div><div class="form-group"><label class="form-label">Observaciones</label><input class="form-input" id="pvO" placeholder="Notas opcionales"></div></div>';
modal.open('Nueva Compra',h,'<button class="btn btn-ghost" id="mCancel">Cancelar</button><button class="btn btn-success" id="mSaveProv"><i class="fas fa-save"></i> Registrar</button>','lg');
document.getElementById('mCancel')?.addEventListener('click',()=>modal.close());
document.getElementById('mSaveProv')?.addEventListener('click',saveCompra);
document.getElementById('pvPr')?.addEventListener('change',pvTallas);
['pvC','pvPrU'].forEach(id=>document.getElementById(id)?.addEventListener('input',calcTotal));
if(cats.length)document.getElementById('pvP')?.addEventListener('change',function(){if(this.value&&document.getElementById('pvPText'))document.getElementById('pvPText').value=this.value;});
function setMode(m){const isU=m==='unif';document.getElementById('pvUnifF').style.display=isU?'':'none';document.getElementById('pvOtroF').style.display=isU?'none':'';document.getElementById('pvModeUnif').className='btn '+(isU?'btn-success':'btn-ghost');document.getElementById('pvModeOtro').className='btn '+(isU?'btn-ghost':'btn-success');}
document.getElementById('pvModeUnif')?.addEventListener('click',()=>setMode('unif'));
document.getElementById('pvModeOtro')?.addEventListener('click',()=>setMode('otro'));
pvTallas();}
function pvTallas(){const p=document.getElementById('pvPr')?.value;if(!p)return;const tallas=getTallasOpts(p);const sel=document.getElementById('pvT');if(sel)sel.innerHTML=tallas.map(t=>'<option>'+t+'</option>').join('');}
function calcTotal(){const c=parseFloat(document.getElementById('pvC')?.value)||0;const pu=parseFloat(document.getElementById('pvPrU')?.value)||0;const tot=document.getElementById('pvTot');if(tot)tot.value='$'+(c*pu).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2});}
function saveCompra(){const isOtro=document.getElementById('pvOtroF')?.style.display!=='none';const sel=document.getElementById('pvP');const txt=document.getElementById('pvPText');const prov=((txt?.value||'').trim()||sel?.value||'').trim();if(!prov){notify('Escribe o selecciona un proveedor','warning');return;}const cant=parseInt(document.getElementById('pvC')?.value,10)||0;const precio=parseFloat(document.getElementById('pvPrU')?.value)||0;if(cant<=0||precio<=0){notify('Completa cantidad y precio unitario','warning');return;}const fecha=document.getElementById('pvF')?.value||today();const ref=document.getElementById('pvR')?.value||'';const obs=document.getElementById('pvO')?.value||'';if(isOtro){const art=(document.getElementById('pvArt')?.value||'').trim();if(!art){notify('Escribe el nombre del artículo','warning');return;}const cat=(document.getElementById('pvCatL')?.value||'').trim()||'General';const s=getStore();if(!s.comprasAlmacen)s.comprasAlmacen=[];const e5aid=Date.now().toString();
s.comprasAlmacen.push({id:e5aid,fecha,articulo:art,categoria:cat,cantidad:cant,precioUnitario:precio,proveedor:prov,referencia:ref,observaciones:obs});
saveComprasAlmacen();
// ETAPA 5 — Actualizar inventario general
if(!s.inventario)s.inventario=[];
const e5item=s.inventario.find(i=>(i.nombre||'').toLowerCase().trim()===(art||'').toLowerCase().trim());
if(e5item){
  const e5ant=e5item.cantidad;
  e5item.cantidad=e5ant+cant;
  e5item.updatedAt=new Date().toISOString();
  log('STOCK_ALM_COMPRA',art+' +'+cant+' ('+e5ant+'→'+e5item.cantidad+') Prov:'+prov,'PROVEEDORES');
}else{
  s.inventario.push({id:'inv_'+e5aid,nombre:art,categoria:'OTROS',cantidad:cant,unidad:'piezas',minStock:0,descripcion:'Creado desde compra',foto:null,updatedAt:new Date().toISOString()});
  log('STOCK_ALM_NUEVO',art+' ×'+cant+' (artículo nuevo) Prov:'+prov,'PROVEEDORES');
}
saveInventario();
log('COMPRA_ALMACEN',cant+'x '+art+' de '+prov);
modal.close();notify('Compra registrada y stock actualizado ✓','success');renderComprasRows();}else{const prenda=document.getElementById('pvPr')?.value;const talla=document.getElementById('pvT')?.value;if(!prenda||!talla){notify('Selecciona prenda y talla','warning');return;}const e5id=Date.now().toString();
getStore().proveedores.push({id:e5id,proveedor:prov,prenda,talla,cantidad:cant,precioUnitario:precio,fecha,referencia:ref,observaciones:obs});
saveProveedores();
// ETAPA 5 — Actualizar stockUniformes
const s5u=getStore();if(!s5u.stockUniformes)s5u.stockUniformes=[];
s5u.stockUniformes.push({id:'prov_'+e5id,prenda,talla,cantidad:cant,costoUnit:precio,fecha,proveedor:prov,factura:ref,observaciones:obs,registradoPor:'Compra',tipo:'entrada_compra'});
saveStockUniformes();
log('STOCK_UNIF_COMPRA',cant+'×'+prenda+' T'+talla+' → stockUniformes','PROVEEDORES');
log('COMPRA',cant+'x '+prenda+' T:'+talla+' de '+prov);
modal.close();notify('Compra registrada y stock actualizado ✓','success');renderComprasRows();}}
function delCompra(id){if(!confirm('¿Seguro que deseas eliminar este registro? Esta acción no se puede deshacer.'))return;const s=getStore();const idx=s.proveedores.findIndex(p=>p.id===id);if(idx>=0){s.proveedores.splice(idx,1);saveProveedores();log('DEL_COMPRA',id);notify('Eliminado','success');renderComprasRows();}}
function delCompraAlm(id){if(!confirm('¿Seguro que deseas eliminar este registro? Esta acción no se puede deshacer.'))return;const s=getStore();s.comprasAlmacen=s.comprasAlmacen||[];const idx=s.comprasAlmacen.findIndex(c=>c.id===id);if(idx>=0){s.comprasAlmacen.splice(idx,1);saveComprasAlmacen();log('DEL_COMPRA_ALM',id);notify('Eliminado','success');renderComprasRows();}}
function attachComprasEvents(){document.getElementById('provNewCompra')?.addEventListener('click',openNuevaCompra);const reset=()=>{comprasVisibleLimit=PAGE_SIZE;renderComprasRows();};['pvFP'].forEach(id=>document.getElementById(id)?.addEventListener('change',reset));document.getElementById('pvFS')?.addEventListener('input',reset);document.getElementById('pvFClear')?.addEventListener('click',()=>{document.getElementById('pvFP').value='';document.getElementById('pvFS').value='';reset();});document.getElementById('pvVerMas')?.addEventListener('click',()=>{comprasVisibleLimit+=PAGE_SIZE;renderComprasRows();});document.getElementById('pvTB')?.addEventListener('click',e=>{const dl=e.target.closest('.pv-del');if(dl)delCompra(dl.dataset.id);const da=e.target.closest('.pv-del-alm');if(da)delCompraAlm(da.dataset.id);});}
function renderCatalogo(){const cats=getCats();let h='<div class="kpi-grid"><div class="kpi info"><div class="kpi-label">Proveedores Registrados</div><div class="kpi-value">'+cats.length+'</div></div></div>';h+='<div id="catGrid" class="form-row c3" style="align-items:start;margin-top:16px"></div>';document.getElementById('provTabContent').innerHTML=h;document.getElementById('provHeaderBtn').innerHTML='<button class="btn btn-success" id="catNewProv"><i class="fas fa-plus"></i> Nuevo Proveedor</button>';renderCatGrid();document.getElementById('catNewProv')?.addEventListener('click',()=>openProvModal(null));document.getElementById('catGrid')?.addEventListener('click',e=>{const ed=e.target.closest('.cat-edit');const dl=e.target.closest('.cat-del');const card=e.target.closest('.cat-card');if(ed){openProvModal(ed.dataset.id);return;}if(dl){delProv(dl.dataset.id);return;}if(card)openProvDetalle(card.dataset.id);});}
function renderCatGrid(){const cats=getCats();const comprasLegacy=getComprasLegacy();const grid=document.getElementById('catGrid');if(!grid)return;if(!cats.length){grid.innerHTML='<div style="grid-column:1/-1" class="empty-state"><i class="fas fa-address-book"></i><p>Sin proveedores en el catálogo</p><p class="text-xs text-muted mt-2">Agrégalos aquí para seleccionarlos rápido al registrar compras</p></div>';return;}grid.innerHTML=cats.map(c=>{const hist=getHistorialProveedor(c);const compras=comprasLegacy.filter(p=>normProv(p.proveedor)===normProv(c.nombre)).length+hist.entradas.length;const totalLegacy=comprasLegacy.filter(p=>normProv(p.proveedor)===normProv(c.nombre)).reduce((sum,p)=>sum+p.cantidad*p.precioUnitario,0);const totalGasto=totalLegacy+hist.entradas.reduce((sum,e)=>sum+e._monto,0);return'<div class="card cat-card" data-id="'+c.id+'" style="cursor:pointer"><div class="card-body" style="padding:18px"><div style="display:flex;align-items:center;gap:10px;margin-bottom:12px"><div style="width:44px;height:44px;background:#dbeafe;border-radius:10px;display:flex;align-items:center;justify-content:center;flex-shrink:0"><i class="fas fa-truck" style="color:#2563eb;font-size:18px"></i></div><div style="flex:1;min-width:0"><p class="font-bold" style="font-size:14px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(c.nombre)+'</p>'+(c.contacto?'<p class="text-xs text-muted">'+esc(c.contacto)+'</p>':'')+'</div></div>'+(getProvPhone(c)?'<p class="text-xs mb-1"><i class="fas fa-phone mr-1 text-muted"></i>'+esc(getProvPhone(c))+'</p>':'')+(c.email?'<p class="text-xs mb-1"><i class="fas fa-envelope mr-1 text-muted"></i>'+esc(c.email)+'</p>':'')+(c.notas?'<p class="text-xs text-muted mt-1 mb-2">'+esc(c.notas)+'</p>':'')+'<div style="display:flex;justify-content:space-between;padding:8px 0;border-top:1px solid var(--border);margin-top:8px"><div><p class="text-xs text-muted">Compras</p><p class="font-bold">'+compras+'</p></div><div style="text-align:right"><p class="text-xs text-muted">Gasto total</p><p class="font-bold" style="color:var(--success)">'+fmtMoney(totalGasto)+'</p></div></div><div class="text-xs text-muted mb-2"><i class="fas fa-eye mr-1"></i>Click para ver historial</div><div class="flex gap-2 mt-2"><button class="btn btn-ghost btn-sm cat-edit" data-id="'+c.id+'" style="flex:1"><i class="fas fa-edit"></i></button><button class="btn btn-ghost btn-sm cat-del" data-id="'+c.id+'" style="flex:1;color:var(--danger)"><i class="fas fa-trash"></i></button></div></div></div>';}).join('');}
function openProvDetalle(id){const c=getCats().find(x=>x.id===id);if(!c)return;const hist=getHistorialProveedor(c);const ultima=hist.ultima;const productos=hist.surtidos.length?hist.surtidos.map(p=>'<span class="badge badge-neutral" style="margin:2px">'+esc(p.nombre||p.sku||p.id)+'</span>').join(''):'<span class="text-muted">Sin productos asociados</span>';const rows=hist.entradas.length?hist.entradas.slice(0,12).map(e=>'<tr><td class="text-xs font-mono">'+fmtDate((e.fecha_hora||e.fecha||'').slice(0,10))+'</td><td class="font-bold">'+esc(e.numero||e.factura_folio||e.id)+'</td><td style="text-align:center">'+e._lineas.length+'</td><td style="text-align:right;color:var(--success);font-weight:700">'+fmtMoney(e._monto)+'</td></tr>').join(''):'<tr><td colspan="4" class="empty-state"><i class="fas fa-file-invoice"></i><p>Sin entradas de recepción relacionadas</p></td></tr>';let h='<div class="kpi-grid mb-4"><div class="kpi info"><div class="kpi-label">Total comprado este año</div><div class="kpi-value">'+fmtMoney(hist.totalAnio)+'</div></div><div class="kpi success"><div class="kpi-label">Última compra</div><div class="kpi-value" style="font-size:18px">'+(ultima?fmtDate((ultima.fecha_hora||ultima.fecha||'').slice(0,10)):'—')+'</div><div class="text-xs text-muted">'+(ultima?fmtMoney(ultima._monto):'Sin compras')+'</div></div><div class="kpi"><div class="kpi-label">Productos que surte</div><div class="kpi-value">'+hist.surtidos.length+'</div></div></div>';h+='<div class="card mb-4"><div class="card-head"><h3>Datos de contacto</h3></div><div class="card-body"><div class="form-row c2"><p><strong>Contacto:</strong> '+esc(c.contacto||'—')+'</p><p><strong>Teléfono:</strong> '+esc(getProvPhone(c)||'—')+'</p><p><strong>Email:</strong> '+esc(c.email||'—')+'</p><p><strong>Notas:</strong> '+esc(c.notas||'—')+'</p></div></div></div>';h+='<div class="card mb-4"><div class="card-head"><h3>Productos que surte</h3></div><div class="card-body">'+productos+'</div></div>';h+='<div class="card"><div class="card-head"><h3>Historial de compras</h3></div><div class="table-wrap"><table class="dt"><thead><tr><th>Fecha</th><th>Entrada / Factura</th><th style="text-align:center">Productos</th><th style="text-align:right">Monto</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>';modal.open(c.nombre,h,'<button class="btn btn-ghost" id="mCloseProv">Cerrar</button>','lg');document.getElementById('mCloseProv')?.addEventListener('click',()=>modal.close());}
function openProvModal(id){const cats=getCats();const c=id?cats.find(x=>x.id===id):null;let h='<div class="form-row c2 mb-3"><div class="form-group"><label class="form-label">Nombre *</label><input class="form-input" id="cpN" value="'+esc(c?.nombre||'')+'" placeholder="Ej: Uniformes García S.A."></div><div class="form-group"><label class="form-label">Contacto / nombre de persona</label><input class="form-input" id="cpCon" value="'+esc(c?.contacto||'')+'" placeholder="Nombre del representante"></div></div><div class="form-row c2 mb-3"><div class="form-group"><label class="form-label">Teléfono</label><input class="form-input" id="cpTel" value="'+esc(getProvPhone(c))+'" placeholder="55 1234 5678" type="tel"></div><div class="form-group"><label class="form-label">Email</label><input class="form-input" id="cpEmail" value="'+esc(c?.email||'')+'" placeholder="correo@proveedor.com" type="email"></div></div><div class="form-group"><label class="form-label">Notas</label><textarea class="form-input" id="cpNotas" rows="3" placeholder="Condiciones de pago, plazos, acuerdos o datos internos...">'+esc(c?.notas||'')+'</textarea></div>';modal.open(id?'Editar Proveedor':'Nuevo Proveedor',h,'<button class="btn btn-ghost" id="mCancel">Cancelar</button><button class="btn btn-success" id="mSaveCat"><i class="fas fa-save"></i> Guardar</button>');document.getElementById('mCancel')?.addEventListener('click',()=>modal.close());document.getElementById('mSaveCat')?.addEventListener('click',()=>{const nom=(document.getElementById('cpN')?.value||'').trim();if(!nom){notify('Escribe el nombre del proveedor','warning');return;}const contacto=document.getElementById('cpCon')?.value||'';const telefono=document.getElementById('cpTel')?.value||'';const email=document.getElementById('cpEmail')?.value||'';const notas=document.getElementById('cpNotas')?.value||'';const cats2=getCats();if(id){const existing=cats2.find(x=>x.id===id);if(existing){existing.nombre=nom;existing.contacto=contacto;existing.telefono=telefono;existing.tel=telefono;existing.email=email;existing.notas=notas;}}else{cats2.push({id:Date.now().toString(),nombre:nom,contacto,telefono,tel:telefono,email,notas});}saveCats(cats2);modal.close();notify('Proveedor guardado','success');renderCatGrid();});}
function delProv(id){const cats=getCats();const c=cats.find(x=>x.id===id);if(!c||!confirm('¿Eliminar "'+c.nombre+'"?\nSus compras registradas se conservan.'))return;saveCats(cats.filter(x=>x.id!==id));notify('Proveedor eliminado','success');renderCatGrid();}
function attachTabEvents(){document.querySelectorAll('.tab-btn').forEach(btn=>{btn.addEventListener('click',function(){currentTab=this.dataset.tab;document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));this.classList.add('active');if(currentTab==='compras')renderCompras();else renderCatalogo();});});}
export function init(){attachTabEvents();if(currentTab==='compras')renderCompras();else renderCatalogo();}
