import{REGLAS,PERFILES,CATEGORIAS}from'./config.js';import{getStore}from'./storage.js';import{normPrenda}from'./utils.js';import{getAreaRule,initAreasRules}from'./areas-config.js';
export function getReglas(emp){
  initAreasRules();
  const perfil=(emp&&emp.perfilDotacion)||'AUTO';
  if(perfil&&perfil!=='AUTO'){
    if(perfil==='PUERTAS_NO_SINDICALIZADO')return getAreaRule('PUERTAS')||REGLAS['PUERTAS'];
    return PERFILES[perfil]||getAreaRule(emp&&emp.area)||REGLAS[emp&&emp.area];
  }
  return getAreaRule(emp&&emp.area)||REGLAS[emp&&emp.area];
}
export function verificarCaptura(emp){const r=getReglas(emp);if(!r)return false;if(r.esFlexible)return emp.capturadoManual===true;if(!emp.tallas)return false;for(const prenda of r.prendas){if(r.opciones&&r.opciones[prenda]){if(!r.opciones[prenda].some(op=>emp.tallas[op]&&emp.tallas[op].trim()!==''))return false;}else{if(!emp.tallas[prenda]||emp.tallas[prenda].trim()==='')return false;}}return true;}
export function getCantPrenda(emp,prendaOriginal){const r=getReglas(emp);if(!r)return 1;if(r.cantidades&&r.cantidades[prendaOriginal])return r.cantidades[prendaOriginal];for(const g in(r.opciones||{})){if((r.opciones[g]||[]).includes(prendaOriginal))return(r.cantidades&&r.cantidades[g])||1;}return 1;}
export function calcStats(){const s=getStore();const act=s.employees.filter(e=>e.estado==='activo');const bajas=s.employees.filter(e=>['baja','movimiento','incapacidad'].includes(e.estado));const cap=act.filter(e=>verificarCaptura(e));return{total:s.employees.length,activos:act.length,bajas:bajas.length,capturados:cap.length,pendientes:act.length-cap.length,pct:act.length?((cap.length/act.length)*100).toFixed(1):'0'};}
export function calcStatsArea(area){const s=getStore();const ae=s.employees.filter(e=>e.area===area);const act=ae.filter(e=>e.estado==='activo');const bajas=ae.filter(e=>['baja','movimiento','incapacidad'].includes(e.estado));const cap=act.filter(e=>verificarCaptura(e));return{total:ae.length,activos:act.length,bajas:bajas.length,capturados:cap.length,pendientes:act.length-cap.length,pct:act.length?((cap.length/act.length)*100).toFixed(0):'0'};}
export function calcTotalesDetallados(){const s=getStore();const det={};s.employees.forEach(emp=>{if(['baja','movimiento','incapacidad'].includes(emp.estado))return;if(!emp.tallas)return;Object.entries(emp.tallas).forEach(([prendaOriginal,talla])=>{if(!talla)return;const cantidad=getCantPrenda(emp,prendaOriginal);const prenda=normPrenda(prendaOriginal);if(!det[prenda])det[prenda]={};if(!det[prenda][talla])det[prenda][talla]={base:0,stock:0,total:0};det[prenda][talla].base+=cantidad;});});Object.entries(s.stockExtra).forEach(([prendaOriginal,tallas])=>{Object.entries(tallas||{}).forEach(([talla,cant])=>{const prenda=normPrenda(prendaOriginal);const n=Math.max(0,parseInt(cant,10)||0);if(!det[prenda])det[prenda]={};if(!det[prenda][talla])det[prenda][talla]={base:0,stock:0,total:0};det[prenda][talla].stock+=n;});});Object.keys(det).forEach(p=>{Object.keys(det[p]).forEach(t=>{det[p][t].total=(det[p][t].base||0)+(det[p][t].stock||0);});});return det;}
export function generarDatosTablero(){const det=calcTotalesDetallados();const datos=[];Object.entries(det).forEach(([articulo,tallas])=>{const cat=CATEGORIAS[articulo]||'OTROS';Object.entries(tallas).forEach(([talla,obj])=>{datos.push({categoria:cat,articulo,talla:talla==='UNITALLA'?'Sin talla':talla,base:obj.base||0,stock:obj.stock||0,cantidad:obj.total||0});});});datos.sort((a,b)=>{if(a.categoria!==b.categoria)return a.categoria.localeCompare(b.categoria);if(a.articulo!==b.articulo)return a.articulo.localeCompare(b.articulo);return(parseInt(a.talla,10)||999)-(parseInt(b.talla,10)||999);});return datos;}
