import{TIPO_TALLA}from'./config.js';import{getStore,saveSalidas,log}from'./storage.js';import{esc,fmtDate,today,getTallasOpts}from'./utils.js';import{notify,modal}from'./ui.js';
function renderTable(){const s=getStore();let h='';h+='<div class="page-head"><div class="page-title"><h1>Salidas de Inventario</h1><p>Mermas, daños y ajustes</p></div><button class="btn btn-danger" id="salNew"><i class="fas fa-sign-out-alt"></i> Nueva Salida</button></div>';h+='<div class="card"><div class="table-wrap"><table class="dt"><thead><tr><th>Fecha</th><th>Prenda</th><th>Talla</th><th>Cantidad</th><th>Motivo</th><th>Obs</th></tr></thead><tbody>';if(s.salidas.length){s.salidas.slice().reverse().forEach(sal=>{h+='<tr><td class="text-xs">'+fmtDate(sal.fecha)+'</td><td class="font-bold">'+esc(sal.prenda)+'</td><td>'+esc(sal.talla)+'</td><td style="color:var(--danger);font-weight:700">-'+sal.cantidad+'</td><td><span class="badge badge-neutral">'+esc(sal.motivo||'—')+'</span></td><td class="text-xs text-sec">'+esc(sal.observaciones||'')+'</td></tr>';});}else{h+='<tr><td colspan="6" class="empty-state"><i class="fas fa-sign-out-alt"></i><p>No hay salidas registradas</p></td></tr>';}h+='</tbody></table></div></div>';return h;}
export function render(){return renderTable();}
function reRenderAndInit(){document.getElementById('mainContent').innerHTML=renderTable();attachEvents();}
function newSalida(){const pl=Object.keys(TIPO_TALLA);let h='<div class="form-row c2"><div class="form-group"><label class="form-label">Prenda *</label><select class="form-select" id="salP">'+pl.map(p=>'<option>'+p+'</option>').join('')+'</select></div><div class="form-group"><label class="form-label">Talla *</label><select class="form-select" id="salT"></select></div><div class="form-group"><label class="form-label">Cantidad *</label><input type="number" class="form-input" id="salC" min="1" value="1"></div><div class="form-group"><label class="form-label">Fecha</label><input type="date" class="form-input" id="salF" value="'+today()+'"></div><div class="form-group"><label class="form-label">Motivo</label><select class="form-select" id="salM"><option>Merma</option><option>Daño</option><option>Devolución</option><option>Ajuste</option><option>Otro</option></select></div><div class="form-group"><label class="form-label">Obs</label><input class="form-input" id="salO"></div></div>';modal.open('Registrar Salida',h,'<button class="btn btn-ghost" id="mCancel">Cancelar</button><button class="btn btn-danger" id="mSaveSal"><i class="fas fa-save"></i> Registrar</button>');document.getElementById('mCancel').addEventListener('click',()=>modal.close());document.getElementById('mSaveSal').addEventListener('click',saveSalida);document.getElementById('salP').addEventListener('change',salTallas);salTallas();}
function salTallas(){const p=document.getElementById('salP')?.value;if(!p)return;const tallas=getTallasOpts(p);const sel=document.getElementById('salT');if(sel)sel.innerHTML=tallas.map(t=>'<option>'+t+'</option>').join('');}
function saveSalida(){const prenda=document.getElementById('salP')?.value;const talla=document.getElementById('salT')?.value;const cant=parseInt(document.getElementById('salC')?.value,10)||0;if(!prenda||!talla||cant<=0){notify('Completa campos','warning');return;}getStore().salidas.push({id:Date.now().toString(),prenda,talla,cantidad:cant,fecha:document.getElementById('salF')?.value||'',motivo:document.getElementById('salM')?.value||'',observaciones:document.getElementById('salO')?.value||''});saveSalidas();log('SALIDA',cant+'x '+prenda+' '+talla);modal.close();notify('Salida registrada','success');reRenderAndInit();}
function attachEvents(){document.getElementById('salNew')?.addEventListener('click',newSalida);}
export function init(){attachEvents();}
