import{calcTotalesDetallados}from'./rules.js';import{getStore,setStockExtra,getStockExtra}from'./storage.js';import{esc,fmt,sortTallas,getTallasOpts}from'./utils.js';import{notify,modal}from'./ui.js';
function renderTable(){const det=calcTotalesDetallados();let h='';h+='<div class="page-head"><div class="page-title"><h1>Totales por Prenda y Talla</h1><p>Base + Stock extra</p></div><div class="flex gap-2"><button class="btn btn-warning" id="totStock"><i class="fas fa-warehouse"></i> Stock</button><button class="btn btn-success" id="totExport"><i class="fas fa-file-excel"></i> Exportar</button></div></div>';if(det['ZAPATO ESPECIAL']){const totE=Object.values(det['ZAPATO ESPECIAL']).reduce((s,o)=>s+o.total,0);h+='<div class="card mb-4" style="border-left:4px solid var(--warning)"><div class="card-head" style="background:var(--warning-light)"><h3><i class="fas fa-shoe-prints mr-2"></i>ZAPATO ESPECIAL — '+fmt(totE)+' pares</h3></div><div class="card-body"><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px">';sortTallas('ZAPATO ESPECIAL',Object.entries(det['ZAPATO ESPECIAL'])).forEach(p=>{h+='<div style="text-align:center;background:var(--surface-alt);padding:12px;border-radius:8px"><div class="font-bold" style="color:var(--primary)">'+p[0]+'</div><div style="font-size:22px;font-weight:800;color:var(--success)">'+p[1].total+'</div>'+(p[1].stock?'<div class="text-xs text-muted">Base '+p[1].base+' <span class="badge badge-info" style="font-size:10px">+'+p[1].stock+'</span></div>':'')+'</div>';});h+='</div></div></div>';}Object.keys(det).filter(p=>p!=='ZAPATO ESPECIAL').forEach(prenda=>{const tallas=det[prenda];const tot=Object.values(tallas).reduce((s,v)=>s+v.total,0);h+='<div class="card mb-4"><div class="card-head"><h3>'+esc(prenda)+'</h3><span class="font-bold" style="color:var(--success)">Total: '+fmt(tot)+'</span></div><div class="card-body"><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(90px,1fr));gap:8px">';sortTallas(prenda,Object.entries(tallas)).forEach(p=>{h+='<div style="text-align:center;background:var(--surface-alt);padding:10px 6px;border-radius:6px"><div class="text-xs font-bold text-sec">'+p[0]+'</div><div style="font-size:20px;font-weight:800;color:var(--primary)">'+p[1].total+'</div>'+(p[1].stock?'<div class="text-xs"><span class="badge badge-info" style="font-size:9px">+'+p[1].stock+'</span></div>':'')+'</div>';});h+='</div></div></div>';});return h;}
export function render(){return renderTable();}
function reRenderAndInit(){document.getElementById('mainContent').innerHTML=renderTable();attachEvents();}
function openStock(){const pl=['PLAYERA POLO TIPO A','PLAYERA POLO TIPO B','CAMISOLA','PLAYERA PANTS','PANTS','PANTALON','BOTA','CHOCLO','ZAPATO ESPECIAL','TENIS','SANDALIAS','CHALECO','CHAMARRA','GORRA','TOALLA','TERMO','SOMBRILLA'].filter(p=>getTallasOpts(p));let h='<div class="form-group"><label class="form-label">Prenda</label><select class="form-select" id="stkP">'+pl.map(p=>'<option>'+p+'</option>').join('')+'</select></div><div id="stkI"></div>';modal.open('Stock Extra',h,'<button class="btn btn-ghost" id="mCancel">Cerrar</button>','lg');document.getElementById('mCancel').addEventListener('click',()=>modal.close());document.getElementById('stkP').addEventListener('change',renderStockInputs);renderStockInputs();}
function renderStockInputs(){const p=document.getElementById('stkP')?.value;if(!p)return;const tallas=getTallasOpts(p);const box=document.getElementById('stkI');if(!box)return;const total=tallas.reduce((s,t)=>s+getStockExtra(p,t),0);box.innerHTML='<div class="flex justify-between items-center mb-3"><span class="font-bold">'+p+'</span><span class="badge badge-info" style="font-size:13px;padding:6px 14px">Total: '+total+'</span></div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(100px,1fr));gap:8px">'+tallas.map(t=>{const v=getStockExtra(p,t);return'<div class="form-group"><label class="form-label">'+t+'</label><input type="number" min="0" class="form-input stk-input" data-prenda="'+p+'" data-talla="'+t+'" value="'+v+'"></div>';}).join('')+'</div>';box.querySelectorAll('.stk-input').forEach(inp=>{inp.addEventListener('change',function(){setStockExtra(this.dataset.prenda,this.dataset.talla,this.value);renderStockInputs();});});}
function exportTotales(){const det=calcTotalesDetallados();const rows=[['Prenda','Talla','Base','Stock','Total']];Object.entries(det).forEach(([p,tallas])=>{Object.entries(tallas).forEach(([t,o])=>{rows.push([p,t,o.base,o.stock,o.total]);});});const ws=XLSX.utils.aoa_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Totales');XLSX.writeFile(wb,'Totales_ASAABLOY.xlsx');notify('Exportado','success');}
function attachEvents(){document.getElementById('totStock')?.addEventListener('click',openStock);document.getElementById('totExport')?.addEventListener('click',exportTotales);}
export function init(){attachEvents();}
