import{NAV}from'./config.js';import{esc,areaClass}from'./utils.js';import{verificarCaptura}from'./rules.js';
let charts={};
export function notify(msg,type){type=type||'info';const wrap=document.getElementById('notifWrap');const icons={info:'fa-info-circle',success:'fa-check-circle',warning:'fa-exclamation-triangle',error:'fa-times-circle'};const el=document.createElement('div');el.className='notif '+type;el.innerHTML='<i class="fas '+(icons[type]||icons.info)+'"></i><span>'+esc(msg)+'</span>';wrap.appendChild(el);setTimeout(()=>{el.style.opacity='0';el.style.transform='translateX(100%)';el.style.transition='all .3s';setTimeout(()=>el.remove(),300);},4000);}
export const modal={open(title,body,foot,size){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modalFoot').innerHTML=foot||'';document.getElementById('modalBox').className='modal-box '+(size||'md');document.getElementById('modalOverlay').classList.add('open');},close(){document.getElementById('modalOverlay').classList.remove('open');}};
export function destroyCharts(){Object.keys(charts).forEach(k=>{try{charts[k].destroy();}catch(e){}});charts={};}
export function createChart(id,cfg){if(charts[id])try{charts[id].destroy();}catch(e){}const el=document.getElementById(id);if(!el)return null;charts[id]=new Chart(el,cfg);return charts[id];}
export function confirm(msg){return window.confirm(msg);}
export function buildNav(currentView){const nav=document.getElementById('sidebarNav');let html='';NAV.forEach(n=>{if(n.section){html+='<div class="nav-section">'+n.section+'</div>';return;}const active=currentView===n.id?' active':'';html+='<div class="nav-item'+active+'" data-view="'+n.id+'"><i class="fas '+n.icon+'"></i><span class="sidebar-label">'+n.label+'</span></div>';});nav.innerHTML=html;}
export function buildAreaBadge(area){return'<span class="badge-area '+areaClass(area)+'">'+esc(area)+'</span>';}
export function buildStatusBadge(emp){const baja=['baja','movimiento','incapacidad'].includes(emp.estado);if(baja)return'<span class="badge badge-neutral">'+emp.estado.toUpperCase()+'</span>';return verificarCaptura(emp)?'<span class="badge badge-success">COMPLETO</span>':'<span class="badge badge-warning">PENDIENTE</span>';}
export function setupEvents(navigate){document.getElementById('modalOverlay').addEventListener('click',function(e){if(e.target===this)modal.close();});document.getElementById('modalClose').addEventListener('click',()=>modal.close());document.getElementById('sidebarToggle').addEventListener('click',()=>{document.getElementById('sidebar').classList.toggle('collapsed');const ic=document.getElementById('sidebarIcon');ic.className=document.getElementById('sidebar').classList.contains('collapsed')?'fas fa-chevron-right':'fas fa-chevron-left';});document.getElementById('hamburger').addEventListener('click',()=>{const sb=document.getElementById('sidebar');sb.classList.toggle('mobile-open');let overlay=document.querySelector('.mobile-overlay');if(!overlay){overlay=document.createElement('div');overlay.className='mobile-overlay';document.body.appendChild(overlay);overlay.addEventListener('click',()=>{sb.classList.remove('mobile-open');overlay.classList.remove('show');});}overlay.classList.toggle('show');});document.getElementById('sidebarNav').addEventListener('click',function(e){const item=e.target.closest('.nav-item');if(item&&item.dataset.view){navigate(item.dataset.view);const sb=document.getElementById('sidebar');sb.classList.remove('mobile-open');const overlay=document.querySelector('.mobile-overlay');if(overlay)overlay.classList.remove('show');}});}
