const CACHE_NAME='uniformes-aa-v37';
const ICONS_CACHE='uniformes-aa-icons-v2';
const APP_SHELL=['./','./index.html','./css/styles.css','./icons/icon-192.png','./icons/icon-512.png','./js/app.js','./js/config.js','./js/utils.js','./js/storage.js','./js/rules.js','./js/ui.js','./js/dashboard.js','./js/empleados.js','./js/captura.js','./js/entregas.js','./js/tablero.js','./js/proveedores.js','./js/inventario.js','./js/importar.js','./js/exportar.js','./js/config-view.js','./js/user-roles.js','./js/delivery-evidence.js','./js/kpi-metrics.js','./js/signature-capture.js','./js/offline-storage.js','./js/operator-delivery.js','./js/admin-dashboard.js','./js/advanced-reports.js','./js/mod-auth.js','./js/mod-entregas-v2.js','./js/mod-entregas-v2-ui.js','./js/mod-costos-base.js','./js/users.js','./js/areas-config.js','./js/centro-costos.js','./js/campanias.js','./js/stock-uniformes.js','./js/supabase-client.js','./js/sync-engine.js','./js/bitacora.js','./js/sku-api.js','./js/inventario-sku.js','./js/entrega-sku.js','./js/devolucion-sku.js','./js/almacen-api.js','./js/recepcion.js','./js/salidas-almacen.js','./js/devoluciones.js','./js/reportes.js','./manifest.json'];
const CDN_ASSETS=['https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js','https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js','https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js','https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css','https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(APP_SHELL.map(u=>new Request(u,{cache:'reload'})))).then(()=>Promise.allSettled(CDN_ASSETS.map(u=>caches.open(CACHE_NAME).then(c=>c.add(new Request(u,{mode:'cors'})))))));self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE_NAME&&x!==ICONS_CACHE).map(x=>caches.delete(x)))));self.clients.claim();});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(!u.protocol.startsWith('http'))return;if(u.pathname.match(/\/icons\/icon-\d+\.png$/)){e.respondWith(caches.open(ICONS_CACHE).then(c=>c.match(e.request).then(h=>{if(h)return h;return fetch(e.request).then(r=>{if(r.ok){c.put(e.request,r.clone());return r;}throw new Error('404');}).catch(()=>genIcon(u.pathname).then(b=>{const rg=new Response(b,{headers:{'Content-Type':'image/png','Cache-Control':'public, max-age=31536000'}});c.put(e.request,rg.clone());return rg;}));})));return;}if(u.origin===self.location.origin){if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).then(r=>{const c=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,c));return r;}).catch(()=>caches.match(e.request).then(c=>c||caches.match('./index.html'))));return;}e.respondWith(caches.match(e.request).then(h=>{if(h)return h;return fetch(e.request).then(r=>{if(r.ok){const c=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,c));}return r;}).catch(()=>undefined);}));return;}e.respondWith(fetch(e.request).then(r=>{if(r.ok){const c=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,c));}return r;}).catch(()=>caches.match(e.request)));});
function genIcon(p){const s=parseInt(p.match(/icon-(\d+)\.png/)[1],10);if(typeof OffscreenCanvas!=='undefined'){const c=new OffscreenCanvas(s,s);const x=c.getContext('2d');draw(x,s);return c.convertToBlob({type:'image/png'}).then(b=>b.arrayBuffer());}return Promise.resolve(new ArrayBuffer(0));}
function draw(c,s){const r=s*.16;c.fillStyle='#0f172a';c.beginPath();c.moveTo(r,0);c.lineTo(s-r,0);c.quadraticCurveTo(s,0,s,r);c.lineTo(s,s-r);c.quadraticCurveTo(s,s,s-r,s);c.lineTo(r,s);c.quadraticCurveTo(0,s,0,s-r);c.lineTo(0,r);c.quadraticCurveTo(0,0,r,0);c.closePath();c.fill();c.fillStyle='#2563eb';c.font='900 '+Math.round(s*.5)+'px "Arial Black",Arial,sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText('AA',s/2,s/2+s*.04);}
self.addEventListener('message',e=>{if(e.data&&e.data.type==='CACHE_ICONS'){caches.open(ICONS_CACHE).then(c=>{e.data.icons.forEach(i=>{const u=new URL(i.url,self.location.origin).href;const r=new Response(i.blob,{headers:{'Content-Type':'image/png','Cache-Control':'public, max-age=31536000'}});c.put(u,r);});});}});
